export type DialogueScene = {
  id: string;
  order: number;
  chapter: string;
  date: string;
  location: string;
  speaker: string;
  direction: string;
  line: string;
  background: string;
  character: string;
};

export const initialDialogue: DialogueScene[] = [
  {
    "id": "scene-01",
    "order": 1,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "speaker": "이야기",
    "direction": "",
    "line": "1981년 1월 12일 밤 11시 40분. 청와대 정책실의 불은 자정이 가까워져도 꺼지지 않았다. 보고서 다섯 권 가운데 하나만, 이상할 만큼 얇았다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": ""
  },
  {
    "id": "scene-02",
    "order": 2,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "speaker": "전두광",
    "direction": "전두광이 가장 얇은 보고서를 탁자 가운데로 밀었다.",
    "line": "그래서. 당장은 멀쩡한데, 이대로 가면 나라가 망한다?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/02_listening_v1.png"
  },
  {
    "id": "scene-03",
    "order": 3,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "speaker": "서문태 정책실장",
    "direction": "밤샘으로 충혈된 서문태의 눈이 잠깐 흔들렸다.",
    "line": "당장은 아닙니다. 하지만 지금만 보고 달리면 이십 년 뒤에는 남의 기술과 남의 돈에 나라의 목줄이 잡힙니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/01_policy_pitch_v1.png"
  },
  {
    "id": "scene-04",
    "order": 4,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "speaker": "백기현 비서실장",
    "direction": "백기현은 안경을 벗어 천천히 닦았다.",
    "line": "각하 앞에서 나라 앞날이 어둡다고 했으니, 자네 앞날도 같이 어두워질 수 있겠어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/baek_gihyeon/03_warning_v2.png"
  },
  {
    "id": "scene-05",
    "order": 5,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "speaker": "강인철 경제수석",
    "direction": "강인철의 연필이 1981년에서 2000년으로 긴 선을 그었다.",
    "line": "지금은 공장 세우고 물건을 찍는 쪽이 이깁니다. 하지만 미래에는 어떤 기술에 돈을 넣고, 어떤 회사를 살릴지 정하는 사람이 공장 몇 개보다 더 큰 힘을 갖게 됩니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/kang_incheol/02_explain_v2.png"
  },
  {
    "id": "scene-06",
    "order": 6,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "전두광",
    "direction": "전두광이 「요보호아동 시설 현황」 표지를 손가락으로 두 번 두드렸다.",
    "line": "공장도, 인구도, 법도 두꺼운데 아이들 보고서만 이 모양이군. 미래를 말하면서, 미래에 살 아이들은 뺐나?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/05_pressure_v1.png"
  },
  {
    "id": "scene-07",
    "order": 7,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "이야기",
    "direction": "",
    "line": "수출산업, 인구전망, 국가계좌, 특별법. 네 권은 벽돌처럼 두꺼웠다. 「요보호아동 시설 현황」만 종잇장처럼 얇았다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": ""
  },
  {
    "id": "scene-08",
    "order": 8,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "서문태 정책실장",
    "direction": "서문태의 손이 가장 얇은 보고서 위에서 멈췄다.",
    "line": "국가는 이미 아이들에게 밥과 잠자리를 줍니다. 이제는 내일을 고를 힘도 줘야 합니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/04_exhausted_concession_v1.png"
  },
  {
    "id": "scene-09",
    "order": 9,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "윤미라 사회교육수석",
    "direction": "윤미라가 손바닥으로 탁자를 내리쳤다.",
    "line": "미치셨습니까? 아이들을 국가가 키우는 자본이나 실험쥐로 보겠다는 겁니까? 실패하면 그 아이 인생은 누가 책임집니까!",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/yoon_mira/03_objection_v1.png"
  },
  {
    "id": "scene-10",
    "order": 10,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "전두광",
    "direction": "전두광은 대답 대신 보고서 표지를 두 번 두드렸다.",
    "line": "먹이고 재우는 데서 끝내면 세금 낭비지. 스스로 돈을 벌게 만들면 투자가 되고.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/04_cold_laugh_v1.png"
  },
  {
    "id": "scene-11",
    "order": 11,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "백기현 비서실장",
    "direction": "백기현이 안경을 다시 쓰며 정치적 손익을 셌다.",
    "line": "핏덩이들에게 나랏돈을 줬다가 잃으면 혈세 낭비라 할 겁니다. 벌면 나라가 코 묻은 돈을 빼앗는다고 할 테고요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/baek_gihyeon/02_advice_v2.png"
  },
  {
    "id": "scene-12",
    "order": 12,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "서문태 정책실장",
    "direction": "서문태가 기다렸다는 듯 새 계좌 양식을 펼쳤다.",
    "line": "열네 살, SEED 01부터 시작합니다. 원금은 만 원입니다. 작아서 우스워 보여도, 손실 이유를 감추기엔 충분히 큰 돈입니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/02_searching_chart_v1.png"
  },
  {
    "id": "scene-13",
    "order": 13,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "전두광",
    "direction": "만년필 끝이 손실 처리 칸 위에서 멈췄다.",
    "line": "잃으면?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/03_calculating_v1.png"
  },
  {
    "id": "scene-14",
    "order": 14,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "서문태 정책실장",
    "direction": "서문태가 다음 달 주문 한도 칸을 손가락으로 짚었다.",
    "line": "아이 빚으로 남기지 않습니다. 대신 다음 달 주문 한도를 깎습니다. 벌면 일부를 국가가 회수하고요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/03_rebuttal_v1.png"
  },
  {
    "id": "scene-15",
    "order": 15,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "전두광",
    "direction": "전두광은 20%에 동그라미를 치고 「미래양성원」 네 글자를 갈겨썼다.",
    "line": "이십 퍼센트. 나머지는 아이 몫. 대신 왜 샀고 왜 팔았는지 전부 쓰게 해. 잘한 이야기만 말고, 손실로 바닥까지 내려간 기록도.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/01_signing_v1.png"
  },
  {
    "id": "scene-16",
    "order": 16,
    "chapter": "1장 · 사람을 자본으로 만드는 밤",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "speaker": "윤미라 사회교육수석",
    "direction": "윤미라는 80% 아래에 ‘아이 명의’라고 힘주어 적었다.",
    "line": "그 80퍼센트는 시설 돈이 아닙니다. 아이 이름으로 묶어두고, 열아홉에 1원도 빠짐없이 넘기십시오.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/yoon_mira/04_solution_v1.png"
  },
  {
    "id": "scene-17",
    "order": 17,
    "chapter": "2장 · 한 손으로 드는 전부",
    "date": "1982년  ·  미래양성계획 출범",
    "location": "국립 미래양성원 · 개원 기록",
    "speaker": "이야기",
    "direction": "",
    "line": "이듬해, 국립 미래양성원이 문을 열었다. 환영 문구 대신 정문에는 한 줄이 걸렸다. 「기록 없는 판단은 우연이다」",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orphanage_1982_portrait_cartoon_v1.png",
    "character": ""
  },
  {
    "id": "scene-18",
    "order": 18,
    "chapter": "2장 · 한 손으로 드는 전부",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "speaker": "이야기",
    "direction": "",
    "line": "2000년 1월 2일 오전 6시 42분. 눈을 뜨자 천장의 누런 물자국이 먼저 보였다. 여섯 살 때부터 귀 잘린 토끼 같다고 생각했던 얼룩. 마지막 날인데도 물자국은 그냥 물자국이었다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-19",
    "order": 19,
    "chapter": "2장 · 한 손으로 드는 전부",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "speaker": "민호",
    "direction": "옆 침대 이불이 꿈틀거리더니 민호가 코만 내밀었다.",
    "line": "형아… 진짜 가?",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_minho_farewell_v3.png"
  },
  {
    "id": "scene-20",
    "order": 20,
    "chapter": "2장 · 한 손으로 드는 전부",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "speaker": "나",
    "direction": "나는 지퍼가 잘 닫히지 않는 가방을 무릎으로 눌렀다.",
    "line": "응. 돈 세는 학교래. 그냥 주면 더 좋을 텐데, 세기만 시키면 손가락만 아프잖아.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/03_playful_grin.png"
  },
  {
    "id": "scene-21",
    "order": 21,
    "chapter": "2장 · 한 손으로 드는 전부",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "speaker": "이야기",
    "direction": "모서리가 닳은 왕딱지 두 장이 민호의 이불 위로 날아갔다.",
    "line": "민호가 웃다가 낡은 가방을 보고 입을 다물었다. 나는 왕딱지 한 장만 챙기고 나머지는 민호 이불 위에 던졌다. 가방 안감을 들추자 낯선 쇳조각이 손끝에 걸렸다. 「제5기 · 17번」.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-22",
    "order": 22,
    "chapter": "2장 · 한 손으로 드는 전부",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "speaker": "나",
    "direction": "나는 쇳조각 명찰을 재빨리 바지 주머니에 쑤셔 넣었다.",
    "line": "이름은 칼로 긁어 지워져 있었다. 뒷면에는 더 이상한 말이 파여 있었다. 「17번을 믿지 마.」 …이게 17번 명찰인데, 누구를 믿지 말라는 거야?",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/17_holding_badge.png"
  },
  {
    "id": "scene-23",
    "order": 23,
    "chapter": "2장 · 한 손으로 드는 전부",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "speaker": "박선희 원장",
    "direction": "박선희 원장이 목도리를 한 번 더 단단히 매어주었다.",
    "line": "짐이 가볍다고 주눅 들지 마. 앞으로 채울 게 많다는 뜻이니까. 가서도 이상한 말은 그냥 넘기지 말고 두 번 물어. 그래도 이상하면 장부에 적어 둬. 말은 날아가도 글은 남으니까.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_park_sunhee_farewell_v1.png"
  },
  {
    "id": "scene-24",
    "order": 24,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "이야기",
    "direction": "정문의 돌 표어가 눈발 사이로 드러났다. 「기록 없는 판단은 우연이다」.",
    "line": "버스는 서울을 벗어나 한참을 덜컹거렸다. 눈발 너머로 붉은 벽돌 건물이 나타났다. 학교치고는 담장이 길었고, 공장치고는 창문이 많았다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-25",
    "order": 25,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "아이들",
    "direction": "종이상자와 비닐봉지를 든 아이들의 속삭임이 겹쳤다.",
    "line": "“여기가 그 유명한 데래.”\n“고아원에서 추천받은 애들만 온다던데?”\n“입학식인데 왜 면접장보다 조용해?”",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-26",
    "order": 26,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "수아",
    "direction": "수아가 내 가방이 남긴 삐뚤어진 바퀴 자국을 가리켰다.",
    "line": "야, 가방 바퀴 하나가 눈을 계속 끌고 다녀.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/07_determined_quality_v2.png"
  },
  {
    "id": "scene-27",
    "order": 27,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "나",
    "direction": "나는 한쪽으로 기운 가방을 태연하게 세웠다.",
    "line": "일부러 눈사람 만드는 중이야. 본관 도착할 때쯤 머리까지 붙이려고.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/02_cheerful_laugh.png"
  },
  {
    "id": "scene-28",
    "order": 28,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "이야기",
    "direction": "연필 끝에서 굳은 눈덩이가 후두둑 떨어졌다.",
    "line": "여자아이는 대꾸 대신 쪼그려 앉아 연필로 바퀴의 눈을 긁어냈다. 처음 보는 사이인데도 망설임이 없었다. 이름은 수아라고 했다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/01_neutral_quality_v2.png"
  },
  {
    "id": "scene-29",
    "order": 29,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "김학준",
    "direction": "남색 규정집을 낀 김학준이 우리 옆에 바짝 붙었다.",
    "line": "정문에서 본관까지 420미터. 6분 안에 도착해야 하고, 뛰면 감점이야. 안내문 7쪽에 있어.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png"
  },
  {
    "id": "scene-30",
    "order": 30,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "수아",
    "direction": "수아가 눈을 가늘게 뜨고 김학준의 명찰을 읽었다.",
    "line": "설명서 학준아, 별명 붙이면 안 된다는 규정도 있어?",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/02_warm_smile_quality_v2.png"
  },
  {
    "id": "scene-31",
    "order": 31,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "학준",
    "direction": "학준의 귀끝이 규정집 표지보다 먼저 붉어졌다.",
    "line": "…없어. 그리고 그렇게 부르지 마.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png"
  },
  {
    "id": "scene-32",
    "order": 32,
    "chapter": "3장 · 설명서 학준",
    "date": "2000.01.02  ·  07:31",
    "location": "국립 미래양성원 · 투자전문과정 정문",
    "speaker": "수아",
    "direction": "수아가 깔깔 웃으며 먼저 언덕을 뛰어올랐다.",
    "line": "그럼 합법이네.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/03_bright_laugh_quality_v2.png"
  },
  {
    "id": "scene-33",
    "order": 33,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "이야기",
    "direction": "오래된 형광등 아래, 이름표 열 장이 빈 의자를 지키고 있었다.",
    "line": "강당에는 내빈석도 부모 자리도 없었다. 열 개의 의자만 반원으로 놓여 있었다. 무대 위 나무상자 하나가 더 수상해 보였다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-34",
    "order": 34,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "아이들",
    "direction": "앞자리와 뒷자리에서 서로 다른 소문이 동시에 튀어나왔다.",
    "line": "“남자 둘, 여자 여덟이래.”\n“자리도 성적순일까?”\n“아직 시험도 안 봤는데 무슨 성적이 있어.”",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-35",
    "order": 35,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "구두 소리가 무대에 닿자 웅성거림이 절반쯤 줄었다.",
    "line": "제6기 교육을 맡은 한서윤입니다. 인사는 조금 뒤에 하죠. 여러분 배에서 나는 소리가 더 급해 보이니까.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-36",
    "order": 36,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 나무상자 위에 손바닥을 올렸다.",
    "line": "이 상자 안에는 단팥빵 하나와 500원짜리 동전이 있어요. 식당에서 빵은 300원입니다. 하나만 고르세요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-37",
    "order": 37,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "수아",
    "direction": "수아의 손이 누구보다 먼저 천장을 찔렀다.",
    "line": "동전이요! 빵 사고도 200원 남잖아요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/04_surprised_quality_v2.png"
  },
  {
    "id": "scene-38",
    "order": 38,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 벽시계를 턱으로 가리켰다.",
    "line": "좋아요. 그런데 식당 문은 두 시간 뒤, 열 시에 열립니다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-39",
    "order": 39,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "수아",
    "direction": "말이 끝나자마자 수아의 배에서 작은 소리가 났다.",
    "line": "두 시간이요? …참을 수 있어요. 아마도.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/05_worried_quality_v2.png"
  },
  {
    "id": "scene-40",
    "order": 40,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "학준",
    "direction": "학준은 규정집 모서리를 만지며 상자를 노려봤다.",
    "line": "빵이 얼마나 남았는지, 열 시에 새 빵이 들어오는지부터 알아야 해요. 동전만 보고 고르기엔 모르는 게 너무 많아요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png"
  },
  {
    "id": "scene-41",
    "order": 41,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "나",
    "direction": "나는 열리지 않은 상자 뚜껑을 손가락으로 가리켰다.",
    "line": "그 전에 상자부터 열어봐야 하는 거 아니에요? 선생님이 단팥빵을 벌써 드셨을 수도 있잖아요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/04_curious_question.png"
  },
  {
    "id": "scene-42",
    "order": 42,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "이야기",
    "direction": "한서윤의 입꼬리가 처음으로 아주 조금 올라갔다.",
    "line": "아이들 사이에서 웃음이 터졌다. 한서윤은 화내지 않았다. 오히려 상자 뚜껑 위에 손을 얹고 나를 다시 보았다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-43",
    "order": 43,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "칠판에 네 칸이 그어졌다. 아는 것, 모르는 것, 고른 이유, 생각을 바꿀 조건.",
    "line": "그래요. 아는 게 달라지면 답도 달라집니다. 여기서 제일 먼저 배울 건 돈 버는 법이 아니라, 모르는 걸 모른다고 말하는 법이에요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-44",
    "order": 44,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "출석부가 펼쳐지고 남학생 두 칸, 여학생 여덟 칸이 차례로 확인됐다.",
    "line": "여기 온 아이는 열 명, 남학생 두 명과 여학생 여덟 명입니다. 이번 기수는 여학생이 유난히 많네요. 모두 전국 보호시설의 추천을 받고, 오랫동안 생활 기록을 살핀 끝에 선발됐어요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-45",
    "order": 45,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "지시봉이 숫자, 사람, 판단 세 단어를 천천히 지나갔다.",
    "line": "여긴 간판만 바꾼 고아원도, 부자 흉내를 내는 학원도 아니에요. 숫자 뒤에 있는 사람과 거짓말을 보고, 자기 판단에 책임지는 법을 배우는 곳입니다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-46",
    "order": 46,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "한서윤의 시선이 반원으로 앉은 아이들을 훑었다.",
    "line": "그럼 첫 기록부터 남겨 볼까요? 자기가 왜 뽑혔다고 생각해요?",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/26_포즈5_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-47",
    "order": 47,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "학준",
    "direction": "학준은 기다렸다는 듯 허리를 곧게 폈다.",
    "line": "규칙을 빨리 외우고, 계산을 잘해서요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png"
  },
  {
    "id": "scene-48",
    "order": 48,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "수아",
    "direction": "수아는 옆자리 아이들의 표정을 한번 훑고 대답했다.",
    "line": "사람 얼굴 보면 뭘 좋아하고 싫어하는지 금방 알아서요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/02_warm_smile_quality_v2.png"
  },
  {
    "id": "scene-49",
    "order": 49,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "나",
    "direction": "나는 이유를 찾는 대신 가장 그럴듯한 답부터 꺼냈다.",
    "line": "돈을 많이 벌 것 같아서 뽑은 거 아니에요?",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/16_hands_on_hips.png"
  },
  {
    "id": "scene-50",
    "order": 50,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 웃음을 누르며 되물었다.",
    "line": "지금 가진 돈은 얼마인데요?",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-51",
    "order": 51,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "나",
    "direction": "주머니 속 왕딱지가 손끝에 걸렸다.",
    "line": "왕딱지 한 장이요. 용 그려진 제일 센 거.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/22_victory_fist.png"
  },
  {
    "id": "scene-52",
    "order": 52,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 출석부 내 이름 옆에 짧은 표시를 남겼다.",
    "line": "돈은 빵점. 솔직함은 합격. 뽑힌 이유는 내일부터 직접 찾아보죠.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-53",
    "order": 53,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "이야기",
    "direction": "낡은 명찰의 모서리가 주머니 안에서 허벅지를 찔렀다.",
    "line": "가장 어둡던 형광등이 한 번 떨리고 안정됐다. 열 개의 이름표가 같은 빛을 받았다. 주머니 속 5기 명찰만 혼자 차갑게 식어 있었다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": ""
  },
  {
    "id": "scene-54",
    "order": 54,
    "chapter": "4장 · 왜 하필 너였을까",
    "date": "2000.01.02  ·  08:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "speaker": "한서윤 선생님",
    "direction": "강당 문이 열리고 차가운 복도 공기가 발끝으로 밀려왔다.",
    "line": "자, 이제 오늘은 첫날이니 기숙사 소개를 해줄게요. 짐 챙기고 모두 따라오세요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/26_포즈5_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-55",
    "order": 55,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:05",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "speaker": "이야기",
    "direction": "한서윤이 출석부를 덮고 복도 쪽으로 먼저 걸음을 옮겼다.",
    "line": "열 명의 의자가 한꺼번에 밀렸다. 강당 문 너머로 이어진 복도에는 젖은 운동화 자국과 낯선 방문들이 줄지어 있었다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-56",
    "order": 56,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:05",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 복도 끝 열린 방문을 가리켰다.",
    "line": "복도 끝이 제6기 생활실이에요. 남학생 둘과 여학생 여덟이 방 하나를 함께 씁니다. 침상과 사물함은 한 사람에게 하나씩 돌아가요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-57",
    "order": 57,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:05",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "speaker": "학준",
    "direction": "학준의 규정집이 가슴팍에서 조금 내려갔다.",
    "line": "남학생하고 여학생이 정말 같은 방에서 잔다고요?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png"
  },
  {
    "id": "scene-58",
    "order": 58,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:05",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "speaker": "한서윤 선생님",
    "direction": "한서윤은 열린 방문보다 먼저 복도 안쪽 칸막이실을 가리켰다.",
    "line": "같은 방에서 자지만 남의 침상과 사물함은 허락 없이 건드리지 않습니다. 옷을 갈아입거나 씻을 때는 잠금 칸막이실을 쓰고요. 불편한 일이 생기면 참지 말고 바로 말하세요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-59",
    "order": 59,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:10",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "낡은 경첩이 낮게 울리고 생활실의 따뜻한 공기가 복도로 흘러나왔다.",
    "line": "한서윤이 가장 가까운 방문을 밀었다. 양쪽 벽의 이층침대와 열 개의 사물함, 길쭉한 공용 책상이 한눈에 들어왔다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-60",
    "order": 60,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:10",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 양쪽 이층침대와 사물함을 차례로 짚었다.",
    "line": "아래층과 위층 중 원하는 자리를 먼저 골라 보세요. 자리를 바꾸고 싶을 때는 둘이 합의하고 생활기록표에 적으면 됩니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-61",
    "order": 61,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:10",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "수아가 가장 안쪽 침대를 보며 코끝을 찡긋했다.",
    "line": "그럼 코 고는 사람은 남자든 여자든 창가 자리로 보내도 돼요?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/03_bright_laugh_quality_v2.png"
  },
  {
    "id": "scene-62",
    "order": 62,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:10",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 웃음을 참듯 출석부로 입가를 가렸다.",
    "line": "보내는 건 안 되고, 본인에게 먼저 말하는 건 됩니다. 첫 생활 회의 안건으로 올려도 좋고요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-63",
    "order": 63,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:10",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "나",
    "direction": "나는 창가 쪽 위층 침대 사다리에 손을 얹었다.",
    "line": "맨 위 침대는 먼저 올라가는 사람이 임자예요?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/04_curious_question.png"
  },
  {
    "id": "scene-64",
    "order": 64,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:10",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 공용 책상 위 빈 장부를 펼쳐 보였다.",
    "line": "오늘만 선착순이에요. 짐을 풀고 서로 이름부터 외우세요. 주식 수업은 내일 시작합니다. 주식이 뭔지도 모른다고 생각하고, 회사와 주식 한 주가 무엇인지부터 천천히 배울 거예요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-65",
    "order": 65,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:10",
    "location": "국립 미래양성원 · 기숙사 세면실",
    "speaker": "한서윤 선생님",
    "direction": "세면실 문 안쪽의 잠금쇠가 또각 소리를 냈다.",
    "line": "세면대와 바구니도 한 사람당 하나씩입니다. 씻는 칸과 갈아입는 칸은 문을 잠그고 사용하세요. 같은 방을 쓴다는 말이 서로의 경계까지 없어진다는 뜻은 아니에요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_washroom_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/26_포즈5_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-66",
    "order": 66,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:22",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "세면실에서 돌아온 열 명이 공용 책상의 낡은 의자와 가까운 아래층 침상에 둥글게 나눠 앉았다.",
    "line": "의자가 일곱 개, 사람이 열 명이었다. 셋이 침상 끝에 걸터앉았고, 그중 하나가 나였다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-67",
    "order": 67,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:22",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "누가 기침을 했다. 누가 사물함 문을 괜히 한 번 여닫았다.",
    "line": "아무도 먼저 말하지 않았다. 라디오 잡음이 들렸다가 꺼졌다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-68",
    "order": 68,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:23",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "삼십 초쯤 지났을 때 수아가 손가락으로 허공에 동그라미를 그렸다.",
    "line": "시계 방향. 이름부터. 설명은 없었는데 여덟 명이 동시에 알아들었다. 그게 좀 무서웠다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-69",
    "order": 69,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:23",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김서아",
    "direction": "창가 의자의 김서아가 이름이 적힌 작은 종이 상자를 책상에 반듯하게 놓았다.",
    "line": "김서아. …아, 안녕. 순서 바꿔서 말했네.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/04_shy_appreciative_v1.png"
  },
  {
    "id": "scene-70",
    "order": 70,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:23",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김서아",
    "direction": "서아가 상자를 손끝으로 조금 밀어 원 가운데로 보냈다.",
    "line": "빌려 갈 거 있으면 여기 적어 줘. 종이는 안에 있어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/01_neutral_notebook_v1.png"
  },
  {
    "id": "scene-71",
    "order": 71,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:24",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이지안",
    "direction": "지안은 이름을 말하지 않았다. 대신 알람시계를 뒤집어 뒷판을 열었다.",
    "line": "이거 소리 이상한 거 아까부터 나만 들었어?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/03_focused_repair_v2.png"
  },
  {
    "id": "scene-72",
    "order": 72,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:24",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이지안",
    "direction": "아무도 대답하지 않았다. 지안은 나사 하나를 손바닥에 굴렸다.",
    "line": "…이지안.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/01_neutral_screwdriver_v2.png"
  },
  {
    "id": "scene-73",
    "order": 73,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:25",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "최이서",
    "direction": "맞은편 아래층의 최이서가 무릎 위 실 뭉치를 조용히 자기 쪽으로 당겼다.",
    "line": "최이서.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/01_base_thread_v1.png"
  },
  {
    "id": "scene-74",
    "order": 74,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:25",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "최이서",
    "direction": "그게 끝이었다. 이서는 실 뭉치에서 초록색 실을 한 뼘 뽑아 끊었다. 원이 다음으로 넘어가려는 순간 다시 입을 열었다.",
    "line": "…이름표. 필요한 사람은 말해. 색은 내가 골라.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/08_focused_mending_v1.png"
  },
  {
    "id": "scene-75",
    "order": 75,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:26",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "정아린",
    "direction": "침상 사다리에 등을 대고 앉은 정아린이 벽시계를 세 번째로 확인했다.",
    "line": "정아린. 근데 이거 몇 분 걸려?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/09_counting_explain_v1.png"
  },
  {
    "id": "scene-76",
    "order": 76,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:26",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "수아가 고개를 들었다.",
    "line": "뭐가?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/01_neutral_quality_v2.png"
  },
  {
    "id": "scene-77",
    "order": 77,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:26",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "정아린",
    "direction": "몇 명이 웃었다. 아린은 왜 웃는지 모르는 얼굴이었다.",
    "line": "이 인사. 한 명당 십 초면 백 초인데 벌써 사 분 지났어.\n…아니, 늦으면 점심 시간표가 밀린다고.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/01_base_cheeky_v1.png"
  },
  {
    "id": "scene-78",
    "order": 78,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:27",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "박하은",
    "direction": "책상 모서리의 박하은이 아직 말하지 않은 자리들을 한 번 훑었다.",
    "line": "박하은. 근데 우리 이거 왜 하는지 알아?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/09_explaining_v1.png"
  },
  {
    "id": "scene-79",
    "order": 79,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:27",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "정아린",
    "direction": "아린이 바로 대답했다.",
    "line": "이름 외우려고.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/01_base_cheeky_v1.png"
  },
  {
    "id": "scene-80",
    "order": 80,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:27",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "박하은",
    "direction": "하은이 원을 한 바퀴 더 둘러봤다. 아직 입을 안 뗀 셋에서 눈이 잠깐 멈췄다.",
    "line": "그건 아는데, 이름만 알고 지나가면 내일 또 어색할 것 같아서.\n다들 말 안 해도 돼. 안 하고 싶으면 안 해도 되는 거지?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/06_worried_v1.png"
  },
  {
    "id": "scene-81",
    "order": 81,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:28",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "윤채아",
    "direction": "하은의 말이 끝나자 원이 잠깐 흔들렸다. 침상 쪽에서 손이 하나 올라왔다.",
    "line": "그럼 나는 안 할게.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/01_neutral_tie_v1.png"
  },
  {
    "id": "scene-82",
    "order": 82,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:28",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "윤채아",
    "direction": "하은이 놀란 얼굴로 돌아봤다. 채아는 이미 시선을 무릎으로 내렸다.",
    "line": "…아니, 이름은 할게. 윤채아.\n나머지는 아직 정리가 안 됐어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/04_shy_blush_v1.png"
  },
  {
    "id": "scene-83",
    "order": 83,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:29",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "오지우",
    "direction": "거절이 나오자 오지우가 라디오 볼륨을 올렸다. 잡음이 짧게 방을 채웠다.",
    "line": "여기는 지우 방송국. 방금 제6기 첫 기권자가 나왔습니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/oh_jiwoo/03_breaking_news_excited_v1.png"
  },
  {
    "id": "scene-84",
    "order": 84,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:29",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "윤채아",
    "direction": "채아가 짧게 잘랐다.",
    "line": "기권 아니야.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/07_sulky_pout_v1.png"
  },
  {
    "id": "scene-85",
    "order": 85,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:29",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "오지우",
    "direction": "채아가 처음으로 지우를 똑바로 봤다. 지우는 눈을 안 피했다.",
    "line": "정정합니다. 기권이 아니라 보류라고 합니다.\n…오지우야. 밤에는 이어폰 쓸게.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/oh_jiwoo/05_surprised_correction_v1.png"
  },
  {
    "id": "scene-86",
    "order": 86,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "원이 반 바퀴쯤 남았을 때 수아가 자리에서 일어섰다.",
    "line": "잠깐. 나 먼저 할게. 순서 꼬였잖아.\n한수아. 수아라고 불러. 그리고 나 지금 배고파.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/08_explaining_quality_v2.png"
  },
  {
    "id": "scene-87",
    "order": 87,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "웃음이 터졌다. 굳어 있던 얼굴들이 처음으로 한꺼번에 풀렸다.",
    "line": "아까 강당에서 단팥빵 얘기 들은 다음부터 계속 배고파. 선생님 그거 진짜 나쁜 사람이야.\n봐, 이게 훨씬 낫지.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/03_bright_laugh_quality_v2.png"
  },
  {
    "id": "scene-88",
    "order": 88,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:31",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김학준",
    "direction": "웃음이 잦아들자 학준이 규정집 색인을 손가락으로 눌렀다.",
    "line": "김학준. 안내문 7쪽에 자기소개 순서는 안 정해져 있어. 그래서 방금 순서 바꾼 것도 규정 위반은 아니야.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-89",
    "order": 89,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:31",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "수아가 학준을 봤다.",
    "line": "누가 물어봤어?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/06_annoyed_quality_v2.png"
  },
  {
    "id": "scene-90",
    "order": 90,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:31",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김학준",
    "direction": "학준의 귀끝이 다시 붉어졌다. 규정집은 무릎 위에서 조금 내려갔다.",
    "line": "…아무도 안 물어봤어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-91",
    "order": 91,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:32",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "남은 사람은 나였다. 아홉 개의 얼굴이 동시에 돌아왔다.",
    "line": "할 말을 세 개 준비해 뒀었다. 셋 다 방금 다른 애들이 더 잘 써 버렸다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-92",
    "order": 92,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:32",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "주머니 안에서 왕딱지 모서리를 만졌다.",
    "line": "그 옆에 명찰도 있었다. 그건 안 만졌다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-93",
    "order": 93,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:32",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "나",
    "direction": "나는 남은 의자를 끌어 원 안에 앉았다.",
    "line": "…나 아직 이름 말 안 했지?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-94",
    "order": 94,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:32",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "수아가 바로 대답했다.",
    "line": "안 했어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/01_neutral_quality_v2.png"
  },
  {
    "id": "scene-95",
    "order": 95,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:33",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "나",
    "direction": "빈 가방을 발뒤꿈치로 밀었다.",
    "line": "잘하는 건 아직 모르겠어. 왕딱지는 한 장 있어.\n그리고 아까 가방 바퀴로 눈사람 만든 거, 그거 일부러 한 거였어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-96",
    "order": 96,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:33",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "수아가 웃었다. 이번엔 나만 보고 웃었다.",
    "line": "나는 이름을 결국 말하지 않았다는 걸 밤에 누워서 알았다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-97",
    "order": 97,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:36",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "소개가 끝나자 열 명이 동시에 침상과 사물함으로 흩어졌다.",
    "line": "열 명 중 이름을 끝까지 말한 사람은 아홉이었다. 아무도 그걸 지적하지 않았다.\n창가, 문가, 위층, 아래층. 방금 외운 이름 아홉 개가 침상 번호와 뒤섞였다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-98",
    "order": 98,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:38",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "정아린",
    "direction": "아린이 출입문 가까운 아래층 침상을 가리켰다.",
    "line": "나는 아침 운동 때문에 먼저 나갈 거야. 문가 아래층을 쓰면 다른 사람 사다리를 안 흔들어도 돼. 반대하는 사람 있어?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/04_assigning_tasks_v1.png"
  },
  {
    "id": "scene-99",
    "order": 99,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:40",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "지안이 콘센트 위치를 재다가 드라이버 통을 옆 사물함에 밀어 넣었다.",
    "line": "철문이 닫혔다. 그 소리가 생각보다 컸다.\n사물함 문에 붙은 이름표는 최이서였다. 초록색 실로 꿰맨 글씨였다. 방금 만든 거였다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-100",
    "order": 100,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:41",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "최이서",
    "direction": "이서는 사물함을 다시 열어 통을 꺼내 지안 쪽으로 내밀었다. 아무 말도 안 했다. 지안이 받지 않았다.",
    "line": "…내 칸이야.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/07_firm_boundary_v1.png"
  },
  {
    "id": "scene-101",
    "order": 101,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:41",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이지안",
    "direction": "지안은 통을 받지 않고 사물함 번호를 다시 확인했다.",
    "line": "콘센트가 여기밖에 없었어.\n그리고 안 뒤졌어. 넣기만 했어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/06_annoyed_interrupted_v2.png"
  },
  {
    "id": "scene-102",
    "order": 102,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:42",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "최이서",
    "direction": "지안이 입을 열었다가 닫았다.",
    "line": "그건 물어봤어?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/09_skeptical_inspection_v1.png"
  },
  {
    "id": "scene-103",
    "order": 103,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:42",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "정아린",
    "direction": "아린이 두 사람 사이의 거리를 재듯 한 번 보고 끼어들었다.",
    "line": "콘센트 여기 하나면 그게 문제인 거 아냐? 선생님한테 하나 더 놔 달라고 하면 되잖아.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/09_counting_explain_v1.png"
  },
  {
    "id": "scene-104",
    "order": 104,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:42",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "박하은",
    "direction": "하은이 아린의 말을 막았다.",
    "line": "아린아, 지금 그거 아니야.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/07_sulky_pout_v1.png"
  },
  {
    "id": "scene-105",
    "order": 105,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:43",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "정아린",
    "direction": "아린은 이유를 모르겠다는 얼굴이었다.",
    "line": "왜? 원인 없애면 다시 안 생기는데.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/07_deadline_annoyed_v1.png"
  },
  {
    "id": "scene-106",
    "order": 106,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:43",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "박하은",
    "direction": "하은이 이서 쪽을 가리켰다.",
    "line": "이서 아직 대답 못 받았어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/09_explaining_v1.png"
  },
  {
    "id": "scene-107",
    "order": 107,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:44",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이지안",
    "direction": "지안이 드라이버 통을 자기 가슴에 안았다. 한참 있다가 말했다.",
    "line": "번호를 안 봤어.\n…이름표도 안 봤어. 초록색인 것만 봤어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/07_apologetic_boundary_v2.png"
  },
  {
    "id": "scene-108",
    "order": 108,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:44",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "최이서",
    "direction": "이서가 처음으로 지안을 봤다.",
    "line": "그거 아까 내가 꿰맨 거야.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/02_gentle_smile_v1.png"
  },
  {
    "id": "scene-109",
    "order": 109,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:44",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이지안",
    "direction": "지안이 짧게 대답했다.",
    "line": "알아. 지금 알았어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/01_neutral_screwdriver_v2.png"
  },
  {
    "id": "scene-110",
    "order": 110,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:45",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "박하은",
    "direction": "하은이 공용 책상의 빈 생활기록표를 가운데로 당겼다.",
    "line": "지금 정하자. 이거 또 생겨.\n사물함은 물어보고, 세면실은 노크하고 대답 듣고.\n더 있을 것 같은데, 나는 모르겠어. 불편한 거 있는 사람?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/08_determined_v1.png"
  },
  {
    "id": "scene-111",
    "order": 111,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:46",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "박하은",
    "direction": "아무도 손을 안 들었다.",
    "line": "…없는 게 아니라 말하기 싫은 거지? 그럼 종이에 써서 넣자.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/06_worried_v1.png"
  },
  {
    "id": "scene-112",
    "order": 112,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:47",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김서아",
    "direction": "서아가 규칙을 적다가 고개를 들었다.",
    "line": "네 개야.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/08_determined_record_v1.png"
  },
  {
    "id": "scene-113",
    "order": 113,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:47",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "박하은",
    "direction": "하은이 손가락을 세어 봤다.",
    "line": "세 개 말했는데?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/05_surprised_v1.png"
  },
  {
    "id": "scene-114",
    "order": 114,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:47",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김서아",
    "direction": "서아가 네 번째 줄을 그었다. 그 아래에 열 칸.",
    "line": "종이에 써서 넣기. 그것도 규칙이야. 방금 정했잖아.\n동의하면 직접 써. 남이 대신 쓰면 나중에 아무 소용 없어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/09_explaining_ledger_v1.png"
  },
  {
    "id": "scene-115",
    "order": 115,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:48",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "삐뚤고 반듯한 글씨가 하나씩 늘었다.",
    "line": "반듯한 것, 삐뚤어진 것, 너무 작은 것, 칸을 넘어간 것.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-116",
    "order": 116,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:48",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "윤채아",
    "direction": "아홉 개가 찼을 때 채아가 펜을 들었다가 다시 놓았다.",
    "line": "이거 언제까지 유효해?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/09_explaining_v1.png"
  },
  {
    "id": "scene-117",
    "order": 117,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:49",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김서아",
    "direction": "서아가 펜을 멈췄다.",
    "line": "…생각 안 해 봤어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/05_surprised_record_v1.png"
  },
  {
    "id": "scene-118",
    "order": 118,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:49",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "윤채아",
    "direction": "채아가 표 아래를 짚었다.",
    "line": "그럼 그것도 적어. 언제 다시 정할지.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/08_determined_v1.png"
  },
  {
    "id": "scene-119",
    "order": 119,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:50",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "열 번째 칸이 채워졌다.",
    "line": "방은 조금 덜 낯설어졌고, 각자의 사물함 문은 오히려 전보다 더 분명한 경계가 되었다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-120",
    "order": 120,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:49",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "수아가 내 텅 빈 사물함에 남은 이름표 하나를 붙였다. 「왕딱지 중앙은행」.",
    "line": "예금은 왕딱지만 받고 이자는 웃긴 이야기로 줍니다. 단, 총재가 가진 돈은 현재 한 장입니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/03_bright_laugh_quality_v2.png"
  },
  {
    "id": "scene-121",
    "order": 121,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:50",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "오지우",
    "direction": "지우가 라디오 잡음에 맞춰 짧은 뉴스 진행 목소리를 냈다.",
    "line": "속보입니다. 왕딱지 중앙은행이 개업 첫날부터 현금 부족을 발표했습니다. 예금자 보호는 안 됩니다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/oh_jiwoo/03_breaking_news_excited_v1.png"
  },
  {
    "id": "scene-122",
    "order": 122,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:53",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "윤채아",
    "direction": "웃음이 잦아들자 채아가 열 개의 이름 아래 빈 출신 시설 칸을 바라봤다.",
    "line": "근데 우리는 왜 여기 뽑힌 걸까? 추천서에 뭐라고 적혔는지 본 사람 있어?",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/06_worried_v1.png"
  },
  {
    "id": "scene-123",
    "order": 123,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  09:54",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "아무도 대답하지 않았다. 아는 아이도 없었고, 모른다고 먼저 인정하고 싶은 아이도 없었다.",
    "line": "라디오 잡음만 길게 늘어졌다. 학준은 규정집을 덮었고, 나는 주머니 속 명찰 모서리를 더 세게 눌렀다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-124",
    "order": 124,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "소등 직전, 바지를 접어 사물함에 넣다가 쇳조각이 바닥에 닿았다.",
    "line": "작은 금속음이 났다. 나는 급히 주웠지만 맞은편 아래층의 학준은 이미 몸을 일으킨 뒤였다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-125",
    "order": 125,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  21:35",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김학준",
    "direction": "학준이 다른 침상을 깨우지 않으려 입 모양만 크게 움직였다.",
    "line": "그거 오늘 강당에서도 만졌지? 제5기 명찰 아니야? 규정집 부록에는 제5기 명단이 통째로 빠져 있어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-126",
    "order": 126,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  21:36",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "바로 위 침상에서 수아의 얼굴이 거꾸로 내려왔다.",
    "line": "둘이 비밀 얘기할 때는 목소리보다 이불이 더 시끄러워. 보여 주기 싫으면 안 보여 줘도 돼. 대신 위험한 거면 같이 알아야 해.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/05_worried_quality_v2.png"
  },
  {
    "id": "scene-127",
    "order": 127,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  21:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "나",
    "direction": "나는 손바닥을 아주 조금 펼쳐 「제5기 · 17번」과 긁혀 지워진 이름을 보여 줬다.",
    "line": "보육원 가방 안감에서 나왔어. 뒤에는 ‘17번을 믿지 마’라고 적혀 있어. 아직 선생님한테는 말하지 않았어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-128",
    "order": 128,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  21:38",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "김학준",
    "direction": "학준은 규정집의 빈 뒷장을 찢지 않고 페이지 번호만 접어 표시했다.",
    "line": "내일 기록실 위치부터 확인하자. 원본은 네가 가지고, 문구와 발견 장소만 따로 적어. 증거 하나를 셋이 들고 다니면 셋 다 잃어버릴 수 있어.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-129",
    "order": 129,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  21:39",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "수아",
    "direction": "수아가 손가락을 입술에 댄 뒤 빈 생활기록표 뒷면을 가리켰다.",
    "line": "어른을 무조건 의심하지도 말고, 무조건 믿지도 말자. 우리 셋이 같은 걸 보고 같은 말로 적은 다음에 묻는 거야.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/07_determined_quality_v2.png"
  },
  {
    "id": "scene-130",
    "order": 130,
    "chapter": "5장 · 열 명이 쓰는 한 방",
    "date": "2000.01.02  ·  21:40",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "소등 뒤에도 창밖의 눈빛이 이층침대 난간에 가늘게 남아 있었다.",
    "line": "밤 아홉 시 사십 분. 열 개의 침상에서 이불이 차례로 부풀었다. 남자 둘과 여자 여덟이 한 방을 쓰는 첫날, 낯선 숨소리 사이로 내일 배울 ‘주식’이라는 말만 오래 잠들지 않았다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-131",
    "order": 131,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  08:40",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "speaker": "이야기",
    "direction": "알람시계가 울리기 전부터 침상 사다리와 사물함 문이 차례로 움직였다.",
    "line": "다음 날 아침 여덟 시 사십 분. 창문으로 들어온 겨울 햇빛이 침상과 사물함을 환하게 훑었다. 세수를 마친 열 명은 공책 한 권씩 챙겼다.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": ""
  },
  {
    "id": "scene-132",
    "order": 132,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  08:55",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 출석부 대신 얇은 PC 좌석표를 들고 복도 끝으로 걸었다.",
    "line": "첫 수업은 교실이 아니라 PC 실습실에서 합니다. 앞으로 주식 수업은 각자 자기 컴퓨터로 화면을 직접 보면서 배울 거예요.",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-133",
    "order": 133,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "이야기",
    "direction": "CRT 모니터 열 대가 꺼진 유리 화면으로 아이들을 비췄다.",
    "line": "문이 열리자 베이지색 모니터와 본체가 두 줄로 늘어서 있었다. 학생 자리마다 키보드와 줄 달린 마우스가 하나씩 놓여 있었다.",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": ""
  },
  {
    "id": "scene-134",
    "order": 134,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 중앙 통로에 서서 양쪽 컴퓨터 줄을 펼친 손으로 가리켰다.",
    "line": "자, 여기가 주식 PC 실습실이에요. 오늘부터 한 사람당 컴퓨터 한 대를 맡습니다. 하지만 아직 아무 버튼도 누르지 마세요.",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-135",
    "order": 135,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "학준",
    "direction": "학준의 시선이 전원 버튼과 키보드 사이를 빠르게 오갔다.",
    "line": "컴퓨터를 켜면 바로 주식을 살 수 있는 건가요?",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png"
  },
  {
    "id": "scene-136",
    "order": 136,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 칠판에 회사, 한 주, 가격 세 단어를 크게 적었다.",
    "line": "아니요. 먼저 회사가 무엇인지, 주식 한 주가 그 회사의 얼마나 작은 소유 조각인지부터 배웁니다. 모르는 말은 그 자리에서 바로 풀어 설명할게요.",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png"
  },
  {
    "id": "scene-137",
    "order": 137,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:02",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "한서윤 선생님",
    "direction": "교실 앞의 큰 CRT 화면 두 대에 아직 이름 없는 차트 선만 떠올랐다.",
    "line": "자기 번호 앞에 앉으세요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_investment_room_2000_portrait_cartoon_v1.png",
    "character": "/play/assets/assets/images/주식선생님/08_포즈1_포인터_고해상도_투명.png"
  },
  {
    "id": "scene-138",
    "order": 138,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:02",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "이야기",
    "direction": "열 개의 의자가 끌렸다.",
    "line": "내 자리는 06번이었다. 모니터에 손바닥 자국이 하나 남아 있었다. 내 것보다 컸다.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_investment_room_2000_portrait_cartoon_v1.png",
    "character": ""
  },
  {
    "id": "scene-139",
    "order": 139,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:03",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "한서윤 선생님",
    "direction": "한서윤이 중앙 통로에서 양쪽 줄을 훑어봤다.",
    "line": "오늘은 돈 버는 법 안 가르칩니다. 화면에 뭐가 있는지만 봐요.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_investment_room_2000_portrait_cartoon_v1.png",
    "character": "/play/assets/assets/images/주식선생님/09_포즈2_왼쪽설명_고해상도_투명.png"
  },
  {
    "id": "scene-140",
    "order": 140,
    "chapter": "6장 · PC 열 대가 켜지는 아침",
    "date": "2000.01.03  ·  09:03",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "speaker": "한서윤 선생님",
    "direction": "나는 고개를 들었다.",
    "line": "…그리고 06번.\n그 자리 작년에도 06번이었어요. 그건 나중에 이야기하죠.",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_investment_room_2000_portrait_cartoon_v1.png",
    "character": "/play/assets/assets/images/주식선생님/10_포즈3_양손설명_고해상도_투명.png"
  }
];
