part of 'market_data.dart';

/// 기업 사건의 대분류보다 한 단계 아래에 있는 독립 인과 문법이다.
///
/// 같은 대분류라도 무엇이 먼저 흔들리고, 무엇을 검증하며, 성공과 실패가
/// 어디로 전이되는지가 다르다. 각 기업은 허용 업종 문법 안에서 이 목록을
/// 월드시드별 순열로 소진한 뒤에야 같은 문법을 다시 사용한다.
class FictionalMarketArcScenario {
  const FictionalMarketArcScenario({
    required this.id,
    required this.kind,
    required this.focus,
    required this.leadingSignal,
    required this.upside,
    required this.downside,
  });

  final String id;
  final String kind;
  final String focus;
  final String leadingSignal;
  final String upside;
  final String downside;
}

const _fictionalMarketArcScenarios = <FictionalMarketArcScenario>[
  FictionalMarketArcScenario(
    id: 'breakthrough_yield',
    kind: 'breakthrough',
    focus: '핵심 수율',
    leadingSignal: '시험 생산의 합격률과 재작업 시간이 달라진다',
    upside: '수율 안정으로 단위원가와 공급 신뢰가 함께 개선된다',
    downside: '불량 누적으로 양산 일정과 고객 인증이 밀린다',
  ),
  FictionalMarketArcScenario(
    id: 'breakthrough_efficiency',
    kind: 'breakthrough',
    focus: '전력 효율',
    leadingSignal: '동일 성능에서 소비전력과 발열 수치가 바뀐다',
    upside: '효율 우위가 제품 차별화와 장기 공급계약으로 이어진다',
    downside: '발열과 전력소모가 기준을 넘어서 재설계가 필요해진다',
  ),
  FictionalMarketArcScenario(
    id: 'breakthrough_integration',
    kind: 'breakthrough',
    focus: '기능 통합',
    leadingSignal: '여러 부품과 공정을 하나로 묶는 시제품이 시험된다',
    upside: '부품 수와 조립공정이 줄어 원가·크기 경쟁력이 생긴다',
    downside: '한 기능의 오류가 전체 시스템으로 번져 검증이 중단된다',
  ),
  FictionalMarketArcScenario(
    id: 'breakthrough_miniaturization',
    kind: 'breakthrough',
    focus: '소형화',
    leadingSignal: '부피와 무게를 줄인 설계의 내구시험이 시작된다',
    upside: '소형화가 신규 고객군과 고부가 제품 진입을 연다',
    downside: '열·진동·배선 문제가 생겨 기존 크기로 되돌아간다',
  ),
  FictionalMarketArcScenario(
    id: 'breakthrough_reliability',
    kind: 'breakthrough',
    focus: '장기 신뢰성',
    leadingSignal: '가속수명시험과 극한환경 검증 시간이 늘어난다',
    upside: '수명 기준을 통과해 보증비용과 고객 이탈 우려가 낮아진다',
    downside: '반복 고장으로 보증충당금과 설계변경 비용이 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'breakthrough_interoperability',
    kind: 'breakthrough',
    focus: '상호운용성',
    leadingSignal: '외부 규격·장비와의 호환시험이 집중된다',
    upside: '호환성 확보로 제휴사와 판매채널이 빠르게 늘어난다',
    downside: '표준 충돌로 고객별 맞춤개발 비용이 커진다',
  ),
  FictionalMarketArcScenario(
    id: 'breakthrough_repeatability',
    kind: 'breakthrough',
    focus: '공정 재현성',
    leadingSignal: '연구실 성능을 여러 생산조에서 반복하는 시험이 진행된다',
    upside: '반복생산에서도 성능이 유지돼 양산 전환이 빨라진다',
    downside: '생산조마다 결과가 달라 상용화 신뢰가 무너진다',
  ),
  FictionalMarketArcScenario(
    id: 'breakthrough_cost_curve',
    kind: 'breakthrough',
    focus: '원가 곡선',
    leadingSignal: '시험품의 재료비와 공정시간 절감안이 비교된다',
    upside: '목표원가를 달성해 대중시장 가격으로 진입한다',
    downside: '성능은 확보했지만 원가가 높아 시장이 제한된다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_greenfield',
    kind: 'capacity',
    focus: '신규 생산라인',
    leadingSignal: '부지·장비 발주와 장기 납기 부품 문의가 늘어난다',
    upside: '신규 라인이 예정대로 가동돼 공급 부족을 흡수한다',
    downside: '준공 지연과 감가상각 부담이 현금흐름을 압박한다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_brownfield',
    kind: 'capacity',
    focus: '기존공장 증설',
    leadingSignal: '가동 중인 설비 옆에서 배관·전력 증설이 시작된다',
    upside: '짧은 공사로 생산량을 늘려 투자 회수가 빨라진다',
    downside: '공사 중단이 기존 생산까지 방해해 출하가 줄어든다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_automation',
    kind: 'capacity',
    focus: '공정 자동화',
    leadingSignal: '자동화 장비 반입과 작업자 재배치가 관찰된다',
    upside: '생산속도와 품질이 함께 개선돼 마진이 높아진다',
    downside: '설비 연동 실패로 수작업 복구와 납기 지연이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_outsourcing',
    kind: 'capacity',
    focus: '외주 생산',
    leadingSignal: '협력사 품질심사와 위탁단가 협상이 늘어난다',
    upside: '고정투자 없이 주문 증가에 대응해 자본효율이 높아진다',
    downside: '외주 불량과 납기 통제 실패가 고객 보상으로 번진다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_overseas',
    kind: 'capacity',
    focus: '해외 생산거점',
    leadingSignal: '현지 인허가·채용·부품조달 계약이 동시에 진행된다',
    upside: '관세와 운송비가 줄고 현지 고객 공급이 안정된다',
    downside: '환율·노무·인허가 비용이 예상보다 크게 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_conversion',
    kind: 'capacity',
    focus: '제품군 전환',
    leadingSignal: '기존 라인의 금형·공정 조건이 새 제품에 맞춰 바뀐다',
    upside: '유휴설비가 고수익 제품 생산으로 빠르게 전환된다',
    downside: '전환 수율이 낮아 기존·신제품 공급이 모두 흔들린다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_maintenance',
    kind: 'capacity',
    focus: '정비 병목',
    leadingSignal: '예방정비 기간과 핵심 소모품 주문이 늘어난다',
    upside: '정비 후 고장시간이 줄어 실질 생산능력이 커진다',
    downside: '핵심 장비 고장으로 장기간 생산 공백이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'capacity_quality_gate',
    kind: 'capacity',
    focus: '품질검사 병목',
    leadingSignal: '완성품보다 검사대기 재고가 빠르게 늘어난다',
    upside: '검사 자동화로 출하속도와 품질 추적성이 개선된다',
    downside: '검사 적체가 출하 지연과 재고자금 부담으로 이어진다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_unit_price',
    kind: 'contract',
    focus: '공급단가',
    leadingSignal: '원가 공개 범위와 단가 재협상 회의가 늘어난다',
    upside: '적정 마진을 보장하는 단가로 계약이 확정된다',
    downside: '저가 수주 압박으로 계약을 포기하거나 손실이 예상된다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_minimum_volume',
    kind: 'contract',
    focus: '최소보장 물량',
    leadingSignal: '고객 수요예측과 의무구매 조항이 집중 검토된다',
    upside: '최소 물량 확보로 가동률과 현금흐름이 안정된다',
    downside: '물량 보장 없이 전용설비만 부담하게 된다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_advance',
    kind: 'contract',
    focus: '선수금',
    leadingSignal: '착수금 비율과 지급보증 조건이 막판 조율된다',
    upside: '충분한 선수금으로 운전자금 부담 없이 사업을 시작한다',
    downside: '선투입 비용이 커져 차입과 이자부담이 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_delivery',
    kind: 'contract',
    focus: '인도 일정',
    leadingSignal: '생산 슬롯과 고객 검수일정이 반복 수정된다',
    upside: '현실적인 납기를 확보해 지체상금 위험이 낮아진다',
    downside: '무리한 납기가 공정 지연과 위약금으로 이어진다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_escalation',
    kind: 'contract',
    focus: '원가연동 조항',
    leadingSignal: '원자재 지수와 판매가격 조정식이 협상 쟁점이 된다',
    upside: '원가 상승을 판매가격에 반영해 장기 마진을 방어한다',
    downside: '고정단가 계약이 원자재 상승기에 손실계약으로 변한다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_warranty',
    kind: 'contract',
    focus: '보증책임',
    leadingSignal: '하자 기준과 무상수리 기간을 두고 협상이 길어진다',
    upside: '책임 범위가 명확해 충당금 불확실성이 줄어든다',
    downside: '광범위한 보증책임이 장기 비용으로 남는다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_exclusivity',
    kind: 'contract',
    focus: '독점 공급권',
    leadingSignal: '지역·제품별 독점 범위와 경쟁금지 조항이 검토된다',
    upside: '독점권 확보로 가격 결정력과 고객 잠금효과가 생긴다',
    downside: '독점 의무 때문에 다른 고객 기회를 잃는다',
  ),
  FictionalMarketArcScenario(
    id: 'contract_renewal',
    kind: 'contract',
    focus: '갱신 선택권',
    leadingSignal: '성과기준과 재계약 단가 산식이 논의된다',
    upside: '장기 갱신권으로 수주잔고의 가시성이 높아진다',
    downside: '갱신 실패로 전용 인력과 설비가 유휴상태가 된다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_recall',
    kind: 'safety',
    focus: '현장 리콜',
    leadingSignal: '반품·수리 문의가 특정 생산분에 집중된다',
    upside: '대상 범위를 조기에 좁혀 비용과 신뢰 훼손을 제한한다',
    downside: '전면 회수로 판매중단과 대규모 충당금이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_fire',
    kind: 'safety',
    focus: '화재 위험',
    leadingSignal: '온도·절연·소화설비 점검 기록이 급증한다',
    upside: '원인을 제거하고 안전 인증을 다시 확보한다',
    downside: '화재와 가동중단이 배상·보험료 상승으로 번진다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_contamination',
    kind: 'safety',
    focus: '오염 관리',
    leadingSignal: '원료·클린룸·보관환경의 추가 검사가 시작된다',
    upside: '오염원을 특정해 정상 생산분의 출하를 재개한다',
    downside: '생산분 폐기와 고객 공급중단이 장기화된다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_workplace',
    kind: 'safety',
    focus: '산업재해',
    leadingSignal: '위험공정 작업중지와 안전교육 시간이 늘어난다',
    upside: '공정 개선으로 사고율과 작업손실 시간이 줄어든다',
    downside: '중대사고로 조업정지·수사·보상비가 겹친다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_certification',
    kind: 'safety',
    focus: '안전 인증',
    leadingSignal: '외부 시험기관의 보완 요구와 재시험이 이어진다',
    upside: '필수 인증을 통과해 판매지역이 확대된다',
    downside: '인증 지연으로 출시와 계약 인도가 미뤄진다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_component',
    kind: 'safety',
    focus: '핵심부품 결함',
    leadingSignal: '특정 협력사 부품의 고장률이 상승한다',
    upside: '대체부품 전환으로 고장률을 정상화한다',
    downside: '결함 범위가 확대돼 완제품 교체비가 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_process',
    kind: 'safety',
    focus: '공정 이탈',
    leadingSignal: '작업기록과 기준값 사이의 편차가 발견된다',
    upside: '이탈 구간을 격리하고 추적관리 체계를 강화한다',
    downside: '품질기록 신뢰가 무너져 고객 전수검사가 시작된다',
  ),
  FictionalMarketArcScenario(
    id: 'safety_insurance',
    kind: 'safety',
    focus: '보험 보상',
    leadingSignal: '손해사정과 면책조항 해석이 길어진다',
    upside: '보험금으로 복구비와 영업손실 대부분을 보전한다',
    downside: '면책 판정으로 사고비용을 회사가 직접 부담한다',
  ),
  FictionalMarketArcScenario(
    id: 'security_accounts',
    kind: 'security',
    focus: '계정 침해',
    leadingSignal: '비정상 로그인과 비밀번호 재설정이 급증한다',
    upside: '침해 계정을 빠르게 차단해 고객 피해를 제한한다',
    downside: '대규모 계정 탈취가 이탈과 보상비로 이어진다',
  ),
  FictionalMarketArcScenario(
    id: 'security_payment',
    kind: 'security',
    focus: '결제 부정사용',
    leadingSignal: '취소·환불과 이상거래 탐지 건수가 늘어난다',
    upside: '탐지규칙 개선으로 손실률과 승인오류가 함께 줄어든다',
    downside: '부정거래 배상과 가맹점 신뢰 하락이 겹친다',
  ),
  FictionalMarketArcScenario(
    id: 'security_source',
    kind: 'security',
    focus: '소스코드 유출',
    leadingSignal: '개발망 접근기록과 외부 저장장치 조사가 시작된다',
    upside: '유출 범위를 제한하고 핵심 비밀을 보호한다',
    downside: '핵심 설계가 경쟁사와 공격자에게 노출된다',
  ),
  FictionalMarketArcScenario(
    id: 'security_denial',
    kind: 'security',
    focus: '서비스 마비',
    leadingSignal: '접속폭주와 비정상 트래픽 대응 용량이 시험된다',
    upside: '우회망과 방어설비가 장애시간을 크게 줄인다',
    downside: '장기 접속장애로 매출과 이용자 신뢰가 훼손된다',
  ),
  FictionalMarketArcScenario(
    id: 'security_insider',
    kind: 'security',
    focus: '내부자 위협',
    leadingSignal: '퇴직자·협력사 권한과 자료반출 기록을 재점검한다',
    upside: '과도한 권한을 회수해 추가 유출을 막는다',
    downside: '내부 공모가 확인돼 통제체계 전반을 다시 구축한다',
  ),
  FictionalMarketArcScenario(
    id: 'security_encryption',
    kind: 'security',
    focus: '암호체계',
    leadingSignal: '인증서·암호키 교체와 호환성 검사가 늘어난다',
    upside: '새 암호체계 도입으로 거래 안정성이 높아진다',
    downside: '키 관리 실패로 데이터 복구와 거래 검증이 지연된다',
  ),
  FictionalMarketArcScenario(
    id: 'security_access',
    kind: 'security',
    focus: '접근권한',
    leadingSignal: '관리자 권한과 외부 접속 승인 절차가 강화된다',
    upside: '최소권한 체계로 침해 경로를 제거한다',
    downside: '권한 오남용이 핵심 시스템 조작으로 이어진다',
  ),
  FictionalMarketArcScenario(
    id: 'security_recovery',
    kind: 'security',
    focus: '백업 복구',
    leadingSignal: '재해복구 모의훈련과 백업 무결성 검사가 실시된다',
    upside: '복구목표 시간 안에 서비스를 정상화한다',
    downside: '백업까지 손상돼 데이터와 영업일을 잃는다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_refinancing',
    kind: 'finance',
    focus: '차환 금리',
    leadingSignal: '만기도래 채권과 은행대출의 새 금리가 논의된다',
    upside: '장기 저금리 자금으로 만기와 이자부담을 낮춘다',
    downside: '차환 금리 급등으로 투자와 배당 여력이 줄어든다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_covenant',
    kind: 'finance',
    focus: '재무약정',
    leadingSignal: '부채비율·이자보상 기준의 면제 협상이 시작된다',
    upside: '약정 유예를 받아 강제상환 위험을 피한다',
    downside: '약정 위반으로 조기상환과 담보추가 요구가 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_convertible',
    kind: 'finance',
    focus: '전환증권',
    leadingSignal: '전환가격·리픽싱·콜옵션 조건이 검토된다',
    upside: '낮은 이자로 성장자금을 확보하고 상환부담을 줄인다',
    downside: '대규모 전환 가능성이 주당가치 희석을 키운다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_fx_debt',
    kind: 'finance',
    focus: '외화부채',
    leadingSignal: '환율 변화에 따른 원리금 상환액이 재산정된다',
    upside: '통화 일치와 헤지로 환차손을 제한한다',
    downside: '환율 급등이 부채와 이자비용을 동시에 키운다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_working_capital',
    kind: 'finance',
    focus: '운전자금',
    leadingSignal: '재고일수와 매입·매출 결제조건이 길어진다',
    upside: '재고와 결제주기 단축으로 현금이 빠르게 회수된다',
    downside: '매출 성장에도 현금이 묶여 단기차입이 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_receivables',
    kind: 'finance',
    focus: '매출채권',
    leadingSignal: '주요 고객의 지급지연과 대손평가가 늘어난다',
    upside: '채권 회수와 보증 확보로 대손 위험을 낮춘다',
    downside: '고객 부실이 대규모 대손상각으로 전이된다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_rating',
    kind: 'finance',
    focus: '신용등급',
    leadingSignal: '평가사 자료요청과 재무전망 검토가 강화된다',
    upside: '등급 상향으로 회사채 발행비용이 낮아진다',
    downside: '등급 하향이 담보·금리·거래조건을 악화시킨다',
  ),
  FictionalMarketArcScenario(
    id: 'finance_collateral',
    kind: 'finance',
    focus: '담보 여력',
    leadingSignal: '부동산·설비 가치평가와 추가담보 요구가 진행된다',
    upside: '충분한 담보가 유동성 안전판을 제공한다',
    downside: '담보부족으로 신규자금 조달이 막힌다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_license',
    kind: 'regulation',
    focus: '사업 인허가',
    leadingSignal: '감독기관 보완요구와 현장실사가 이어진다',
    upside: '허가 취득으로 새 시장의 영업이 가능해진다',
    downside: '허가 지연·취소로 투자자산이 유휴화된다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_environment',
    kind: 'regulation',
    focus: '환경 기준',
    leadingSignal: '배출·폐기·에너지 사용량의 추가 측정이 시작된다',
    upside: '기준을 선제 충족해 경쟁사보다 낮은 대응비용을 확보한다',
    downside: '개선명령과 설비투자가 원가를 크게 높인다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_tariff',
    kind: 'regulation',
    focus: '관세·통상',
    leadingSignal: '원산지 증명과 품목분류 자문이 늘어난다',
    upside: '우대관세를 확보해 수출 가격경쟁력이 높아진다',
    downside: '추가관세와 통관지연으로 해외 판매가 위축된다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_subsidy',
    kind: 'regulation',
    focus: '정책 보조금',
    leadingSignal: '지원요건·국산화율·투자기한 검토가 진행된다',
    upside: '보조금과 세액공제로 투자회수 기간이 짧아진다',
    downside: '지원 탈락·환수로 사업성이 급격히 나빠진다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_price',
    kind: 'regulation',
    focus: '가격 규제',
    leadingSignal: '원가자료 제출과 요금·약가 심사가 강화된다',
    upside: '합리적 가격조정을 인정받아 마진을 회복한다',
    downside: '가격동결·인하로 원가 상승을 전가하지 못한다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_privacy',
    kind: 'regulation',
    focus: '개인정보 규정',
    leadingSignal: '동의·보관·제3자 제공 절차가 재점검된다',
    upside: '준법체계를 갖춰 대형 고객의 신뢰를 얻는다',
    downside: '위반 제재와 데이터 활용 제한이 성장성을 낮춘다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_standard',
    kind: 'regulation',
    focus: '제품 표준',
    leadingSignal: '시험규격 변경과 인증서 갱신 요구가 나타난다',
    upside: '새 표준을 먼저 통과해 교체수요를 선점한다',
    downside: '기존 제품 판매중단과 재인증 비용이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'regulation_export',
    kind: 'regulation',
    focus: '수출 통제',
    leadingSignal: '최종사용자 확인과 전략물자 심사가 길어진다',
    upside: '허가와 대체시장을 확보해 수출을 유지한다',
    downside: '핵심 시장·부품 접근 제한으로 매출과 생산이 줄어든다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_price',
    kind: 'competition',
    focus: '가격 인하',
    leadingSignal: '경쟁사 할인과 유통점 보조금이 빠르게 늘어난다',
    upside: '원가우위로 가격경쟁에서도 점유율과 이익을 지킨다',
    downside: '판가 하락이 마진과 브랜드가치를 함께 훼손한다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_entry',
    kind: 'competition',
    focus: '신규 진입자',
    leadingSignal: '새 경쟁사의 채용·설비·유통계약이 관찰된다',
    upside: '기술·고객관계 장벽으로 신규 진입을 막아낸다',
    downside: '빠른 추격으로 핵심 고객과 인력을 빼앗긴다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_substitute',
    kind: 'competition',
    focus: '대체 기술',
    leadingSignal: '고객 시험예산이 다른 방식의 제품으로 이동한다',
    upside: '대체 기술을 흡수해 새 제품군으로 전환한다',
    downside: '기존 제품의 교체주기와 시장규모가 급격히 줄어든다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_channel',
    kind: 'competition',
    focus: '유통채널',
    leadingSignal: '주요 판매점의 진열·수수료·재고조건이 바뀐다',
    upside: '핵심 채널 우선권으로 판매 접점을 확대한다',
    downside: '채널 이탈로 판촉비와 재고가 함께 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_bid',
    kind: 'competition',
    focus: '경쟁 입찰',
    leadingSignal: '제안가격과 기술평가 항목의 수정이 반복된다',
    upside: '기술점수와 총비용 우위로 대형 고객을 확보한다',
    downside: '과도한 가격경쟁으로 수주를 잃거나 저마진을 떠안는다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_talent',
    kind: 'competition',
    focus: '핵심인력',
    leadingSignal: '연구·영업 책임자에 대한 경쟁사 영입 제안이 늘어난다',
    upside: '보상과 조직개편으로 인력·고객관계를 지킨다',
    downside: '집단 이직이 개발일정과 영업망을 흔든다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_compatibility',
    kind: 'competition',
    focus: '호환 생태계',
    leadingSignal: '고객과 협력사가 지원 규격을 다시 선택한다',
    upside: '호환 파트너 확대로 사실상 표준 지위를 얻는다',
    downside: '고립된 규격 때문에 고객 전환비용 우위가 사라진다',
  ),
  FictionalMarketArcScenario(
    id: 'competition_bundle',
    kind: 'competition',
    focus: '묶음 판매',
    leadingSignal: '경쟁사가 주력상품과 서비스를 결합해 가격을 낮춘다',
    upside: '자체 묶음상품으로 고객당 매출과 유지율을 높인다',
    downside: '단품 경쟁력이 약해져 해지와 할인비용이 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_volume',
    kind: 'earnings',
    focus: '판매량',
    leadingSignal: '출하·주문·취소 건수가 기존 계획에서 벗어난다',
    upside: '판매량 증가가 고정비 흡수와 이익 레버리지로 이어진다',
    downside: '판매 부진으로 재고와 가동률 부담이 커진다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_price',
    kind: 'earnings',
    focus: '평균판매가격',
    leadingSignal: '할인율과 고가제품 판매비중이 달라진다',
    upside: '가격 인상과 고급화가 매출총이익률을 높인다',
    downside: '할인 경쟁이 매출보다 빠르게 이익을 깎는다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_mix',
    kind: 'earnings',
    focus: '제품 구성',
    leadingSignal: '저가·고가 제품의 주문 비중이 크게 변한다',
    upside: '고수익 제품 비중 증가로 같은 매출에서도 이익이 늘어난다',
    downside: '저수익 제품 편중으로 외형 성장과 현금이익이 엇갈린다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_utilization',
    kind: 'earnings',
    focus: '가동률',
    leadingSignal: '교대조와 설비 운전시간이 평소 범위를 벗어난다',
    upside: '가동률 상승으로 단위당 고정비가 낮아진다',
    downside: '유휴설비 감가상각이 영업이익을 압박한다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_yield',
    kind: 'earnings',
    focus: '불량·폐기율',
    leadingSignal: '재작업·폐기·반품 수량이 달라진다',
    upside: '불량 감소가 원가와 납기를 동시에 개선한다',
    downside: '폐기와 재작업이 매출총이익을 잠식한다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_marketing',
    kind: 'earnings',
    focus: '판매관리비',
    leadingSignal: '광고·수수료·신규채용 지출이 빠르게 변한다',
    upside: '효율적인 지출이 고객획득과 재구매로 회수된다',
    downside: '매출 반응 없이 판촉비만 늘어 이익이 악화된다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_oneoff',
    kind: 'earnings',
    focus: '일회성 손익',
    leadingSignal: '자산매각·충당금·평가손익 항목이 커진다',
    upside: '비핵심 자산 매각으로 현금과 재무구조가 개선된다',
    downside: '대규모 손상차손이 장부가와 신뢰를 낮춘다',
  ),
  FictionalMarketArcScenario(
    id: 'earnings_cashflow',
    kind: 'earnings',
    focus: '영업현금흐름',
    leadingSignal: '이익과 실제 현금유입의 차이가 확대된다',
    upside: '이익이 현금으로 회수돼 투자·상환 여력이 늘어난다',
    downside: '장부이익과 달리 현금부족이 심해져 외부조달이 필요해진다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_related',
    kind: 'governance',
    focus: '특수관계 거래',
    leadingSignal: '계열사 매입·대여·보증의 이사회 검토가 늘어난다',
    upside: '불리한 내부거래를 정리해 이익 유출을 막는다',
    downside: '사익편취와 손실전가가 확인돼 신뢰가 훼손된다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_succession',
    kind: 'governance',
    focus: '경영승계',
    leadingSignal: '후계자 인사와 지분이동·조직개편이 동시에 나타난다',
    upside: '권한과 책임을 명확히 넘겨 전략 공백을 줄인다',
    downside: '승계 갈등이 투자결정과 핵심인력 이탈로 번진다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_board',
    kind: 'governance',
    focus: '이사회 독립성',
    leadingSignal: '사외이사 추천과 위원회 권한 조정이 진행된다',
    upside: '독립적 감시가 자금배분과 내부통제를 개선한다',
    downside: '거수기 이사회가 문제 투자를 막지 못한다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_audit',
    kind: 'governance',
    focus: '감사·회계통제',
    leadingSignal: '결산자료 제출과 외부감사 질문이 늦어진다',
    upside: '회계오류를 조기에 수정해 신뢰를 회복한다',
    downside: '중대한 왜곡이 확인돼 재작성·제재 가능성이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_treasury',
    kind: 'governance',
    focus: '자기주식',
    leadingSignal: '취득·처분·소각 목적을 두고 이사회 논의가 길어진다',
    upside: '소각과 명확한 원칙으로 주당가치가 높아진다',
    downside: '우호지분 목적 처분이 주주가치 희석 논란을 낳는다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_control',
    kind: 'governance',
    focus: '경영권 분쟁',
    leadingSignal: '지분매집·위임장·주주제안 활동이 급증한다',
    upside: '합의된 개편으로 자산효율과 주주환원이 개선된다',
    downside: '장기 분쟁이 비용·인사·투자 공백을 키운다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_allocation',
    kind: 'governance',
    focus: '자본 배분',
    leadingSignal: '대규모 투자·배당·부채상환 우선순위가 재검토된다',
    upside: '수익성 기준에 맞춘 투자로 자본효율이 높아진다',
    downside: '과잉투자와 낮은 수익률이 기업가치를 훼손한다',
  ),
  FictionalMarketArcScenario(
    id: 'governance_insider',
    kind: 'governance',
    focus: '내부자 지분',
    leadingSignal: '대주주·임원의 지분 변동과 담보계약이 나타난다',
    upside: '책임 있는 지분확대가 장기 이해관계를 맞춘다',
    downside: '담보반대매매와 정보비대칭 우려가 커진다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_single',
    kind: 'supply_chain',
    focus: '단일 공급처',
    leadingSignal: '핵심부품의 대체 공급사 인증이 급해진다',
    upside: '복수 공급망을 확보해 중단 위험을 낮춘다',
    downside: '유일 공급사의 차질이 전체 생산을 멈춘다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_port',
    kind: 'supply_chain',
    focus: '항만·운송 지연',
    leadingSignal: '운송일수와 체선·보관료가 상승한다',
    upside: '대체항로와 선복 확보로 고객 납기를 지킨다',
    downside: '운송 적체가 생산중단과 긴급운송비로 번진다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_bankruptcy',
    kind: 'supply_chain',
    focus: '협력사 부실',
    leadingSignal: '납품업체의 결제지연과 인력감축이 관찰된다',
    upside: '선제 인수·대체조달로 핵심 공급을 유지한다',
    downside: '협력사 파산으로 금형·재고·선급금을 잃는다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_qualification',
    kind: 'supply_chain',
    focus: '대체품 인증',
    leadingSignal: '새 공급품의 내구·호환·고객 승인 시험이 늘어난다',
    upside: '대체품 인증으로 원가와 조달안정성이 개선된다',
    downside: '인증 실패로 비싼 기존 공급처에 계속 의존한다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_capacity',
    kind: 'supply_chain',
    focus: '공급사 생산능력',
    leadingSignal: '장기 발주와 설비 선급금 요구가 커진다',
    upside: '공동증설로 필요한 물량을 우선 확보한다',
    downside: '공급능력 부족으로 주문을 받고도 생산하지 못한다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_route',
    kind: 'supply_chain',
    focus: '교역 경로',
    leadingSignal: '통관·환적·보험 조건이 자주 바뀐다',
    upside: '우회경로와 현지창고로 공급시간을 안정시킨다',
    downside: '경로 폐쇄와 보험료 급등이 원가를 높인다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_inventory',
    kind: 'supply_chain',
    focus: '안전재고',
    leadingSignal: '핵심 원료의 재고일수와 선구매가 늘어난다',
    upside: '적정 안전재고가 단기 품귀를 흡수한다',
    downside: '과잉 선구매 뒤 가격하락으로 재고평가손이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'supply_batch',
    kind: 'supply_chain',
    focus: '불량 생산분',
    leadingSignal: '특정 제조번호의 검사·격리 범위가 넓어진다',
    upside: '문제 생산분만 분리해 정상 공급을 이어간다',
    downside: '추적 실패로 전수교체와 고객 생산중단이 발생한다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_steel',
    kind: 'commodity',
    focus: '강재 가격',
    leadingSignal: '후판·특수강 견적과 납기가 빠르게 변한다',
    upside: '장기구매와 설계절감으로 강재비 상승을 방어한다',
    downside: '강재 급등이 고정가 계약의 손실을 키운다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_energy',
    kind: 'commodity',
    focus: '원유·가스 가격',
    leadingSignal: '연료·나프타·전력 비용 전망이 크게 수정된다',
    upside: '효율 개선과 가격연동으로 에너지비를 전가한다',
    downside: '연료비 급등이 운송·생산 마진을 압박한다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_metals',
    kind: 'commodity',
    focus: '구리·알루미늄',
    leadingSignal: '비철금속 재고와 장기구매 프리미엄이 움직인다',
    upside: '재활용·대체재·헤지로 금속비를 안정시킨다',
    downside: '금속 가격 상승이 부품과 설비원가로 전이된다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_silicon',
    kind: 'commodity',
    focus: '고순도 소재',
    leadingSignal: '고순도 원료의 가동률과 장기계약 가격이 변한다',
    upside: '선구매와 공정절감으로 고순도 소재 부족을 넘긴다',
    downside: '소재 품귀가 생산량과 수율을 동시에 낮춘다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_chemicals',
    kind: 'commodity',
    focus: '산업화학 원료',
    leadingSignal: '용제·수지·촉매 공급가격과 품질편차가 커진다',
    upside: '배합 변경과 공급처 다변화로 원가를 낮춘다',
    downside: '원료 변경이 품질문제와 재인증 비용을 만든다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_grain',
    kind: 'commodity',
    focus: '곡물 가격',
    leadingSignal: '작황·운임·선물가격이 원료 구매계획을 흔든다',
    upside: '산지 다변화와 메뉴 조정으로 식품마진을 지킨다',
    downside: '곡물 급등을 판매가격에 반영하지 못한다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_pulp',
    kind: 'commodity',
    focus: '펄프·포장재',
    leadingSignal: '포장 단가와 납품 상자의 조달기간이 늘어난다',
    upside: '경량화와 재생재 사용으로 포장비를 낮춘다',
    downside: '포장재 부족이 완제품 출하까지 늦춘다',
  ),
  FictionalMarketArcScenario(
    id: 'commodity_carbon',
    kind: 'commodity',
    focus: '배출권·환경비용',
    leadingSignal: '배출량 측정과 감축설비 투자안이 구체화된다',
    upside: '효율투자로 배출비용과 에너지비를 함께 줄인다',
    downside: '배출비용 증가와 설비개조가 이익을 압박한다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_usd',
    kind: 'currency',
    focus: '달러 환율',
    leadingSignal: '달러 매출·원료·차입의 순노출이 다시 계산된다',
    upside: '수출대금과 달러비용의 균형으로 환율 이익을 얻는다',
    downside: '달러비용이 매출보다 커 환차손이 확대된다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_yen',
    kind: 'currency',
    focus: '엔화 환율',
    leadingSignal: '일본산 장비대금과 현지 경쟁가격이 변한다',
    upside: '장비 조달비 하락 또는 수출경쟁력 개선을 얻는다',
    downside: '환율 변화가 부품비와 일본시장 가격을 악화시킨다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_euro',
    kind: 'currency',
    focus: '유로 환율',
    leadingSignal: '유럽 수주대금과 장비 구매계약의 가치가 바뀐다',
    upside: '통화조건 조정으로 유럽 사업의 원화이익을 지킨다',
    downside: '유로 노출이 수주채산성과 부채가치를 악화시킨다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_yuan',
    kind: 'currency',
    focus: '위안화 환율',
    leadingSignal: '중국 생산비·판매가격·송금조건이 재협상된다',
    upside: '현지 매출과 비용을 맞춰 변동성을 낮춘다',
    downside: '통화 움직임이 현지 이익과 가격경쟁력을 깎는다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_hedge',
    kind: 'currency',
    focus: '환헤지 불일치',
    leadingSignal: '실물계약과 선물환 만기·금액의 차이가 커진다',
    upside: '헤지비율을 조정해 영업이익 변동을 낮춘다',
    downside: '과잉헤지가 파생손실과 증거금 부담을 만든다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_borrowing',
    kind: 'currency',
    focus: '외화차입',
    leadingSignal: '차입통화와 영업현금 통화의 불일치가 부각된다',
    upside: '통화전환과 조기상환으로 부채위험을 낮춘다',
    downside: '환율 급변이 원금과 이자를 동시에 키운다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_translation',
    kind: 'currency',
    focus: '해외법인 환산',
    leadingSignal: '현지 실적과 연결 실적 사이의 차이가 커진다',
    upside: '유리한 환산효과가 연결 매출과 자본을 높인다',
    downside: '환산손실이 해외자산 가치와 자본을 낮춘다',
  ),
  FictionalMarketArcScenario(
    id: 'currency_basket',
    kind: 'currency',
    focus: '다중통화 결제',
    leadingSignal: '고객·공급사별 결제통화를 바꾸는 협상이 늘어난다',
    upside: '통화바스켓으로 한 환율에 대한 의존을 낮춘다',
    downside: '복잡한 통화노출이 예상 밖 손실을 만든다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_core',
    kind: 'patent',
    focus: '핵심특허 등록',
    leadingSignal: '심사 보정과 선행기술 대응이 막바지에 들어간다',
    upside: '핵심 권리 확보로 제품·실시료 수익을 보호한다',
    downside: '거절로 독점력과 투자회수 가능성이 낮아진다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_expiry',
    kind: 'patent',
    focus: '특허 만료',
    leadingSignal: '후발제품 준비와 후속특허 유효성 검토가 늘어난다',
    upside: '개량특허와 브랜드로 만료 뒤 점유율을 지킨다',
    downside: '복제·대체제품 진입으로 가격과 매출이 급락한다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_cross_license',
    kind: 'patent',
    focus: '상호사용권',
    leadingSignal: '양측 특허목록과 실시료 상계 협상이 진행된다',
    upside: '상호사용권으로 소송 없이 시장을 확대한다',
    downside: '협상 결렬로 판매제한과 소송비가 커진다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_designaround',
    kind: 'patent',
    focus: '우회 설계',
    leadingSignal: '대체 구조의 성능·원가·침해 여부가 시험된다',
    upside: '우회 설계 성공으로 판매와 마진을 유지한다',
    downside: '성능 저하와 재인증으로 출시가 늦어진다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_standard',
    kind: 'patent',
    focus: '표준필수 권리',
    leadingSignal: '표준 채택과 공정 실시조건 협상이 이어진다',
    upside: '표준 채택으로 광범위한 실시료 기반을 얻는다',
    downside: '과도한 권리주장이 규제·무효심판으로 번진다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_employee',
    kind: 'patent',
    focus: '직무발명 보상',
    leadingSignal: '발명자 기여도와 보상규정 해석이 쟁점이 된다',
    upside: '합리적 보상으로 인재와 권리를 함께 지킨다',
    downside: '분쟁으로 핵심권리와 연구인력이 이탈한다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_trade_secret',
    kind: 'patent',
    focus: '공정 영업비밀',
    leadingSignal: '퇴직자 자료반출과 협력사 보안약정이 조사된다',
    upside: '비밀관리 체계를 입증해 공정우위를 보호한다',
    downside: '비밀성 상실로 경쟁사의 추격비용이 낮아진다',
  ),
  FictionalMarketArcScenario(
    id: 'patent_licensing',
    kind: 'patent',
    focus: '기술 실시료',
    leadingSignal: '선급금·매출연동·지역범위 조건이 조율된다',
    upside: '자본투자 없이 안정적인 실시료 수익을 확보한다',
    downside: '낮은 조건의 장기계약으로 기술가치를 묶어버린다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_product',
    kind: 'litigation',
    focus: '제품책임 소송',
    leadingSignal: '피해범위·인과관계·집단소송 가능성이 검토된다',
    upside: '책임 범위가 제한돼 충당금이 환입된다',
    downside: '배상·리콜·평판 손실이 동시에 커진다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_contract',
    kind: 'litigation',
    focus: '계약분쟁',
    leadingSignal: '납기·검수·해지조항에 대한 법률의견이 엇갈린다',
    upside: '대금과 손해배상을 회수해 현금흐름을 복구한다',
    downside: '위약금과 거래중단으로 수주잔고가 줄어든다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_antitrust',
    kind: 'litigation',
    focus: '경쟁법 조사',
    leadingSignal: '가격·입찰·유통계약 자료 제출 요구가 늘어난다',
    upside: '위법 혐의를 벗고 영업제한 위험을 해소한다',
    downside: '과징금과 계약관행 시정으로 수익모델이 흔들린다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_tax',
    kind: 'litigation',
    focus: '세무 분쟁',
    leadingSignal: '이전가격·공제·관세에 대한 추가자료가 요구된다',
    upside: '과세 취소로 충당금과 현금부담이 줄어든다',
    downside: '추징세·가산세가 투자여력을 낮춘다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_labor',
    kind: 'litigation',
    focus: '고용 소송',
    leadingSignal: '임금·지위·해고 기준에 대한 집단 대응이 시작된다',
    upside: '합의와 제도개선으로 장기 인건비 불확실성을 줄인다',
    downside: '소급임금과 복직비용이 대규모로 발생한다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_environment',
    kind: 'litigation',
    focus: '환경 배상',
    leadingSignal: '오염범위와 정화책임의 감정조사가 진행된다',
    upside: '책임 범위가 제한되고 복구계획이 승인된다',
    downside: '정화·배상·조업제한 비용이 장기화된다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_shareholder',
    kind: 'litigation',
    focus: '주주 소송',
    leadingSignal: '공시·이사회 결정에 대한 주주 자료요구가 늘어난다',
    upside: '절차 적법성을 인정받아 거래 불확실성을 해소한다',
    downside: '거래 취소·손해배상과 경영진 책임이 부각된다',
  ),
  FictionalMarketArcScenario(
    id: 'litigation_ip',
    kind: 'litigation',
    focus: '지식재산 소송',
    leadingSignal: '침해대상·판매금지·손해액 감정이 진행된다',
    upside: '권리를 인정받아 경쟁제품 판매를 제한한다',
    downside: '판매금지와 설계변경이 매출 공백을 만든다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_horizontal',
    kind: 'merger',
    focus: '동종기업 인수',
    leadingSignal: '시장점유율·중복고객·공장 통합효과를 실사한다',
    upside: '규모와 가격협상력이 커지고 중복비용이 줄어든다',
    downside: '고가 인수와 고객이탈로 기대 시너지가 사라진다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_vertical',
    kind: 'merger',
    focus: '수직계열화',
    leadingSignal: '핵심 공급사·판매망의 원가와 계약을 실사한다',
    upside: '조달·유통 통제로 원가와 납기가 안정된다',
    downside: '비효율 사업까지 떠안아 고정비가 늘어난다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_overseas',
    kind: 'merger',
    focus: '해외기업 인수',
    leadingSignal: '현지 규제·환율·노무·고객계약 실사가 진행된다',
    upside: '기술과 해외시장 진입시간을 크게 단축한다',
    downside: '문화·환율·부채 문제로 대규모 손상차손이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_asset',
    kind: 'merger',
    focus: '사업자산 양수',
    leadingSignal: '설비·재고·고객계약을 골라 사는 협상이 진행된다',
    upside: '필요 자산만 인수해 적은 비용으로 생산을 확대한다',
    downside: '숨은 하자와 이전불가 계약으로 자산가치가 낮아진다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_joint_venture',
    kind: 'merger',
    focus: '합작법인',
    leadingSignal: '지분율·기술기여·판매지역·이사회 권한을 조율한다',
    upside: '위험과 자금을 나누며 새 시장에 진입한다',
    downside: '의사결정 교착과 기술유출 우려가 사업을 늦춘다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_divestiture',
    kind: 'merger',
    focus: '비핵심 매각',
    leadingSignal: '사업별 현금흐름과 잠재 인수자 검토가 시작된다',
    upside: '매각대금으로 부채를 줄이고 핵심사업에 집중한다',
    downside: '헐값 매각과 공통비 잔존으로 수익성이 악화된다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_hostile',
    kind: 'merger',
    focus: '적대적 인수',
    leadingSignal: '시장매집·우호지분·방어수단 검토가 급증한다',
    upside: '경쟁입찰로 주주가치와 경영개선 압력이 높아진다',
    downside: '방어비용과 경영공백이 장기 전략을 훼손한다',
  ),
  FictionalMarketArcScenario(
    id: 'merger_carveout',
    kind: 'merger',
    focus: '사업부 분리',
    leadingSignal: '독립회계·인력·계약 이전 작업이 시작된다',
    upside: '사업가치가 선명해지고 독립자금 조달이 가능해진다',
    downside: '중복비용과 고객계약 이탈이 분리효과를 상쇄한다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_wage',
    kind: 'labor',
    focus: '임금 협상',
    leadingSignal: '기본급·성과급·소급적용 범위가 쟁점이 된다',
    upside: '생산성 연동 합의로 비용과 동기를 함께 관리한다',
    downside: '급격한 고정급 상승이 장기 원가를 높인다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_shift',
    kind: 'labor',
    focus: '교대제 개편',
    leadingSignal: '근무조·잔업·설비운전 계획이 반복 수정된다',
    upside: '새 교대제로 가동률과 근무환경이 개선된다',
    downside: '인력 공백과 교육부족으로 생산성이 떨어진다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_strike',
    kind: 'labor',
    focus: '파업·작업중단',
    leadingSignal: '쟁의투표와 대체생산 계획이 동시에 진행된다',
    upside: '조기 합의로 납기와 고객관계를 지킨다',
    downside: '장기 중단이 생산손실·위약금·이탈을 만든다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_skilled',
    kind: 'labor',
    focus: '숙련인력 부족',
    leadingSignal: '특정 직무의 채용기간과 임금제안이 높아진다',
    upside: '훈련과 유지보상으로 핵심기술 인력을 확보한다',
    downside: '인력부족이 수율·품질·개발일정을 악화시킨다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_outsourcing',
    kind: 'labor',
    focus: '외주 인력',
    leadingSignal: '도급범위·단가·안전책임 계약이 재검토된다',
    upside: '전문 외주로 변동수요와 비용을 유연하게 관리한다',
    downside: '통제와 숙련 부족이 품질·안전 문제로 번진다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_safety',
    kind: 'labor',
    focus: '안전협약',
    leadingSignal: '위험작업 중지권과 설비개선 요구가 늘어난다',
    upside: '노사 공동개선으로 사고와 중단시간이 줄어든다',
    downside: '합의 실패로 작업거부와 감독기관 조사가 이어진다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_restructuring',
    kind: 'labor',
    focus: '인력 구조조정',
    leadingSignal: '희망퇴직·전환배치·사업장 통합안이 논의된다',
    upside: '핵심역량을 지키며 고정비를 낮춘다',
    downside: '퇴직비용과 사기저하로 절감효과가 늦어진다',
  ),
  FictionalMarketArcScenario(
    id: 'labor_incentive',
    kind: 'labor',
    focus: '성과보상',
    leadingSignal: '생산·영업·연구의 성과기준이 다시 설계된다',
    upside: '보상과 목표가 맞아 생산성과 인재유지가 개선된다',
    downside: '왜곡된 지표가 무리한 판매·품질저하를 유발한다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_preorder',
    kind: 'product_launch',
    focus: '예약 주문',
    leadingSignal: '예약·취소·중복주문의 실제 전환율이 집계된다',
    upside: '높은 실구매 전환이 초도 생산 확대를 정당화한다',
    downside: '허수 예약과 취소가 과잉재고로 이어진다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_channel',
    kind: 'product_launch',
    focus: '유통 입고',
    leadingSignal: '판매점 초도물량과 재주문 속도가 달라진다',
    upside: '빠른 재주문이 실제 소비자 판매를 확인시킨다',
    downside: '채널 재고만 쌓이고 반품 요구가 커진다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_returns',
    kind: 'product_launch',
    focus: '반품률',
    leadingSignal: '초기 구매자의 반품·교환 사유가 집중된다',
    upside: '낮은 반품과 좋은 재구매가 제품 적합성을 증명한다',
    downside: '높은 반품이 매출취소·재포장·평판손실을 만든다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_warranty',
    kind: 'product_launch',
    focus: '초기 품질',
    leadingSignal: '고객지원 문의와 무상수리 부품 사용량이 늘어난다',
    upside: '초기 고장을 빠르게 수정해 브랜드 신뢰를 지킨다',
    downside: '반복 고장으로 보증충당금과 판매중단이 발생한다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_pricing',
    kind: 'product_launch',
    focus: '출시 가격',
    leadingSignal: '사전 가격조사와 할인·보조금 조건이 바뀐다',
    upside: '고객이 높은 가격을 받아들여 마진과 브랜드가 강화된다',
    downside: '가격 저항으로 조기할인과 재고평가손이 생긴다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_ecosystem',
    kind: 'product_launch',
    focus: '부가 생태계',
    leadingSignal: '액세서리·콘텐츠·서비스 파트너 참여가 달라진다',
    upside: '보완재 확대가 제품 판매와 반복수익을 키운다',
    downside: '지원 생태계 부족으로 고객 활용도가 낮아진다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_region',
    kind: 'product_launch',
    focus: '지역 확장',
    leadingSignal: '언어·인증·유통망별 출시 일정이 조정된다',
    upside: '지역별 단계 출시로 품질을 유지하며 매출을 넓힌다',
    downside: '현지화 실패와 규제지연으로 확장비용만 남는다',
  ),
  FictionalMarketArcScenario(
    id: 'launch_cannibalization',
    kind: 'product_launch',
    focus: '기존제품 잠식',
    leadingSignal: '신제품 주문과 기존제품 취소가 동시에 늘어난다',
    upside: '고객을 경쟁사에 뺏기지 않고 고가 신제품으로 이동시킨다',
    downside: '전체 고객은 늘지 않은 채 저마진 전환비용만 생긴다',
  ),
];

List<FictionalMarketArcScenario>? _publicArcScenarioCache;

List<FictionalMarketArcScenario> get fictionalMarketArcScenarios =>
    _publicArcScenarioCache ??= List<FictionalMarketArcScenario>.unmodifiable(
      _fictionalMarketArcScenarios,
    );
