part of '../main.dart';

// GENERATED FILE. Edit the canonical dialogue JSON, then run npm run dialogue:sync.
const canonicalDialogueScenes = <Map<String, Object>>[
  <String, Object>{
    "order": 1,
    "id": "scene-01",
    "speaker": "이야기",
    "line": "1981년 1월 12일 밤 11시 40분. 청와대 정책실 책상 위에는 물가, 외채, 수출, 인구를 다룬 보고서가 쌓여 있었다. 다섯 권 모두 나라의 미래를 말하고 있었다. 그 미래를 살아갈 아이들에 관한 보고서만, 손가락 한 마디 두께도 되지 않았다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 2,
    "id": "scene-02",
    "speaker": "전두광",
    "line": "결론만 말해. 지금 방식대로 가면 스무 해 뒤엔, 우리가 만든 물건값도 남이 정한다는 건가?",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/02_listening_v1.png",
  },
  <String, Object>{
    "order": 3,
    "id": "scene-03",
    "speaker": "서문태 정책실장",
    "line": "그럴 가능성이 큽니다. 기술도 돈도 밖에서 빌리면 공장은 돌아갑니다. 다만 무엇을 만들고, 어디에 돈을 넣을지는 우리가 정하지 못합니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/01_policy_pitch_v1.png",
  },
  <String, Object>{
    "order": 4,
    "id": "scene-04",
    "speaker": "백기현 비서실장",
    "line": "그 말을 밖에서 그대로 했다간 내일 신문 제목은 정해져 있겠군. ‘정부, 이대로면 나라 망한다 인정.’ 정책보다 제목이 먼저 사람을 잡습니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/baek_gihyeon/03_warning_v2.png",
  },
  <String, Object>{
    "order": 5,
    "id": "scene-05",
    "speaker": "강인철 경제수석",
    "line": "지금은 공장을 많이 가진 쪽이 셉니다. 다음은 다릅니다. 기술을 고르고 자금이 흐를 곳을 정하는 쪽이, 공장 열 채보다 큰 힘을 갖게 될 겁니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 정책실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_policy_room_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/kang_incheol/02_explain_v2.png",
  },
  <String, Object>{
    "order": 6,
    "id": "scene-06",
    "speaker": "전두광",
    "line": "그런데 이건 왜 이렇게 얇아? 수출도 인구도 스무 해 뒤를 보면서, 정작 그때 살아 있을 아이들은 몇 장으로 끝냈군.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/05_pressure_v1.png",
  },
  <String, Object>{
    "order": 7,
    "id": "scene-07",
    "speaker": "이야기",
    "line": "「수출산업 고도화」, 「장기 인구전망」, 「국가계좌 운용안」, 「미래산업 특별법」. 네 권은 책상 위에서 꼼짝도 하지 않았다. 「요보호아동 시설 현황」만 난방기 바람에 표지가 들렸다 내려앉았다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 8,
    "id": "scene-08",
    "speaker": "서문태 정책실장",
    "line": "국가는 아이들에게 밥과 잠자리를 줍니다. 문제는 열아홉이 되는 날입니다. 그날 문밖으로 내보내며 자립하라고 합니다. 고를 돈도, 실패해 본 기록도 주지 않은 채로요.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/04_exhausted_concession_v1.png",
  },
  <String, Object>{
    "order": 9,
    "id": "scene-09",
    "speaker": "윤미라 사회교육수석",
    "line": "그래서 왜 보호아동입니까? 실패해도 항의할 부모가 없어서라면 교육이 아니라 실험입니다. 아이를 국가가 키워 회수할 자산으로 보는 순간, 이 계획은 시작부터 잘못된 겁니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/yoon_mira/03_objection_v1.png",
  },
  <String, Object>{
    "order": 10,
    "id": "scene-10",
    "speaker": "전두광",
    "line": "빈손으로 내보내 놓고 자유를 줬다고 말하는 것도 잘못이지. 실패한 빚을 아이에게 남기지 않는다면, 적어도 선택해 볼 기회는 줄 수 있어.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/03_calculating_v1.png",
  },
  <String, Object>{
    "order": 11,
    "id": "scene-11",
    "speaker": "백기현 비서실장",
    "line": "잃으면 아이들에게 투기를 가르쳤다고 할 겁니다. 벌면 나라가 아이 돈을 떼 간다고 하겠죠. 어느 쪽이든 욕먹을 준비부터 해야 합니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/baek_gihyeon/02_advice_v2.png",
  },
  <String, Object>{
    "order": 12,
    "id": "scene-12",
    "speaker": "서문태 정책실장",
    "line": "그래서 작게 시작합니다. 열네 살, 시범번호 SEED 01. 첫 원금은 오만 원입니다. 인생을 무너뜨릴 돈은 아니지만, 아무 생각 없이 고른 버릇은 드러날 액수입니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/02_searching_chart_v1.png",
  },
  <String, Object>{
    "order": 13,
    "id": "scene-13",
    "speaker": "전두광",
    "line": "전부 잃으면?",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/03_calculating_v1.png",
  },
  <String, Object>{
    "order": 14,
    "id": "scene-14",
    "speaker": "서문태 정책실장",
    "line": "아이의 빚으로 남기지 않습니다. 다음 달 주문 한도만 줄이고, 판단 과정을 다시 쓰게 합니다. 수익이 나면 정해진 비율을 국가가 회수합니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/seo_muntae/03_rebuttal_v1.png",
  },
  <String, Object>{
    "order": 15,
    "id": "scene-15",
    "speaker": "전두광",
    "line": "이십 퍼센트. 나머지는 아이 이름으로 남겨. 대신 산 이유와 판 이유를 전부 기록하게 해. 잘한 선택보다, 틀리고도 숨기지 않은 기록이 더 오래 남을 테니까.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/jeon_dugwang/01_signing_v1.png",
  },
  <String, Object>{
    "order": 16,
    "id": "scene-16",
    "speaker": "윤미라 사회교육수석",
    "line": "그 팔십 퍼센트에는 시설도 공무원도 손대지 못하게 하십시오. 아이 명의 계좌에 묶고 외부 감사를 붙이세요. 열아홉이 되는 날 1원까지 넘긴다는 조항이 없으면 저는 서명하지 않겠습니다.",
    "direction": "",
    "date": "1981.01.12  ·  23:40",
    "location": "청와대 · 미래전략 심야회의",
    "background": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/backgrounds/bg_conference_night_v1.png",
    "character": "/play/assets/assets/images/cinematic_soft_painted/policy_1981/yoon_mira/04_solution_v1.png",
  },
  <String, Object>{
    "order": 17,
    "id": "scene-17",
    "speaker": "이야기",
    "line": "이듬해, 국립 미래양성원이 문을 열었다. 정문에는 환영 문구 대신 한 문장이 걸렸다. 「기록 없는 판단은 우연이다」. 그것이 아이를 지키는 약속인지, 아이를 오래 들여다보기 위한 문장인지는 아직 아무도 몰랐다.",
    "direction": "",
    "date": "1982년  ·  미래양성계획 출범",
    "location": "국립 미래양성원 · 개원 기록",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orphanage_1982_portrait_cartoon_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 18,
    "id": "scene-18",
    "speaker": "이야기",
    "line": "2000년 1월 2일 오전 6시 42분. 눈을 뜨자 천장의 누런 물자국이 먼저 보였다. 여섯 살 때부터 귀 잘린 토끼를 닮았다고 생각했던 얼룩. 새봄보육원에서 보내는 마지막 아침인데도, 토끼는 평소처럼 벽만 보고 있었다.",
    "direction": "",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 19,
    "id": "scene-19",
    "speaker": "민호",
    "line": "형아… 오늘 진짜 가?",
    "direction": "",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_minho_farewell_v3.png",
  },
  <String, Object>{
    "order": 20,
    "id": "scene-20",
    "speaker": "나",
    "line": "응. 돈 배우는 데래. 내 돈은 하나도 없는데 뭘 가르치나, 그거부터 물어보려고.",
    "direction": "",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/03_playful_grin.png",
  },
  <String, Object>{
    "order": 21,
    "id": "scene-21",
    "speaker": "이야기",
    "line": "가방에는 갈아입을 옷 두 벌과 모서리가 닳은 연습장 한 권이 전부였다. 뜯어진 안감을 안쪽으로 밀어 넣다가 손끝에 차가운 쇳조각이 걸렸다. 오래된 명찰이었다. 「제5기 · 17번」.",
    "direction": "",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 22,
    "id": "scene-22",
    "speaker": "나",
    "line": "이름은 일부러 긁어낸 것처럼 지워져 있었다. 뒤에는 더 짧은 문장이 파여 있었다. 「17번을 믿지 마.」 …네가 17번인데, 대체 누구를 믿지 말라는 거야?",
    "direction": "",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/17_holding_badge.png",
  },
  <String, Object>{
    "order": 23,
    "id": "scene-23",
    "speaker": "박선희 원장",
    "line": "짐이 적다고 주눅 들 필요 없어. 앞으로 네 걸로 채우면 되니까. 밥 거르지 말고, 모르는 말은 두 번 물어. 그래도 이상하면 꼭 적어 둬. 남이 한 말보다 네가 남긴 기록이 오래 가.",
    "direction": "",
    "date": "2000.01.02  ·  06:42",
    "location": "새봄보육원 · 2층 다섯 번째 방",
    "background": "/play/assets/assets/images/historical_prologue/bg_orphanage_departure_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_park_sunhee_farewell_v1.png",
  },
  <String, Object>{
    "order": 24,
    "id": "scene-24",
    "speaker": "이야기",
    "line": "버스는 서울을 벗어난 뒤에도 한참을 달렸다. 문 닫은 공장 셔터 옆에는 ‘벤처기업 입주 모집’ 현수막이 펄럭였고, 오래된 전파사 건너편에는 새 PC방 간판이 올라가고 있었다. 망한 자리 위에 새 세상이 들어선다는 말은, 적어도 거리의 간판들만 보면 사실 같았다.",
    "direction": "",
    "date": "2000.01.02  ·  07:31",
    "location": "미래양성원행 버스 · 서울 외곽",
    "background": "/play/assets/assets/images/historical_prologue/bg_bus_transition_seoul_outskirts_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 25,
    "id": "scene-25",
    "speaker": "아이들",
    "line": "“진짜 주식으로 돈을 굴린대.”\n“우리 이름으로 된 계좌도 준다던데?”\n“잃으면 어떻게 되는지는 아무도 모르잖아.”",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 26,
    "id": "scene-26",
    "speaker": "수아",
    "line": "잠깐. 너 가방 바퀴에 눈 꽉 끼었어. 그대로 끌면 진짜 망가질 것 같은데?",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/05_worried_quality_v2.png",
  },
  <String, Object>{
    "order": 27,
    "id": "scene-27",
    "speaker": "나",
    "line": "여기까지 버틴 가방이야. 본관까진 버티겠지.",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/03_playful_grin.png",
  },
  <String, Object>{
    "order": 28,
    "id": "scene-28",
    "speaker": "이야기",
    "line": "여자아이는 대답 대신 쪼그려 앉아 연필 끝으로 바퀴 틈의 눈을 긁어냈다. 처음 본 사이인데도 손이 빨랐다. 일어나며 자기 이름은 한수아라고 했다.",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 29,
    "id": "scene-29",
    "speaker": "김학준",
    "line": "접수는 아홉 시까지야. 지금 여덟 시 오십사 분. 여기서 더 서 있으면 셋 다 늦어.",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 30,
    "id": "scene-30",
    "speaker": "수아",
    "line": "처음 보는 애한테 인사보다 시간부터 말해?",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/06_annoyed_quality_v2.png",
  },
  <String, Object>{
    "order": 31,
    "id": "scene-31",
    "speaker": "김학준",
    "line": "늦고 나서 인사하는 것보단 낫잖아.",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 32,
    "id": "scene-32",
    "speaker": "수아",
    "line": "맞는 말이라 더 얄밉네. 일단 가자. 걸으면서 싸우면 안 늦겠지.",
    "direction": "",
    "date": "2000.01.02  ·  08:54",
    "location": "국립 미래양성원 · 정문",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_academy_gate_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/03_bright_laugh_quality_v2.png",
  },
  <String, Object>{
    "order": 33,
    "id": "scene-33",
    "speaker": "이야기",
    "line": "강당에는 내빈석도 부모 자리도 없었다. 반원으로 놓인 의자 열 개와, 그 앞의 긴 책상 하나뿐이었다. 책상 위에는 번호가 붙은 얇은 통장 열 권이 가지런히 놓여 있었다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 34,
    "id": "scene-34",
    "speaker": "아이들",
    "line": "“저거 진짜 통장 아니야?”\n“내 번호 적혀 있어.”\n“안에 돈도 들어 있나?”",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 35,
    "id": "scene-35",
    "speaker": "한서윤 선생님",
    "line": "제6기 교육을 맡은 한서윤입니다. 긴 입학식은 하지 않을게요. 여러분이 제일 궁금해하는 것부터 확인하죠. 앞에 있는 통장을 펼쳐 보세요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 36,
    "id": "scene-36",
    "speaker": "한서윤 선생님",
    "line": "잔액란에는 오만 원이 찍혀 있습니다. 앞으로 여러분이 직접 운용할 시작금입니다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 37,
    "id": "scene-37",
    "speaker": "수아",
    "line": "이거… 진짜 우리가 쓰는 돈이에요?",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/04_surprised_quality_v2.png",
  },
  <String, Object>{
    "order": 38,
    "id": "scene-38",
    "speaker": "한서윤 선생님",
    "line": "조건을 이해하고 동의한 뒤부터요. 오늘 바로 주식을 사는 건 아닙니다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 39,
    "id": "scene-39",
    "speaker": "김학준",
    "line": "원금을 잃으면 빚으로 남습니까?",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 40,
    "id": "scene-40",
    "speaker": "한서윤 선생님",
    "line": "아니요. 개인 빚은 생기지 않아요. 대신 다음 달 주문 한도가 줄어듭니다. 수익이 나면 이십 퍼센트는 국가가 회수하고, 팔십 퍼센트는 여러분 계좌에 쌓입니다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 41,
    "id": "scene-41",
    "speaker": "나",
    "line": "그럼 돈을 주는 게 목적은 아니네요. 우리가 뭘 고르고, 어디서 틀리는지 보려는 거지.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/04_curious_question.png",
  },
  <String, Object>{
    "order": 42,
    "id": "scene-42",
    "speaker": "이야기",
    "line": "이번에는 아무도 웃지 않았다. 한서윤은 대답을 서두르지 않았다. 통장 열 권을 한 번 훑은 뒤, 내 쪽으로 시선을 돌렸다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 43,
    "id": "scene-43",
    "speaker": "한서윤 선생님",
    "line": "맞아요. 국가는 여러분의 판단 기록을 원합니다. 그 사실을 좋은 말로 감추지는 않을게요. 마음에 들지 않는 조건은 따져 물어도 됩니다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 44,
    "id": "scene-44",
    "speaker": "한서윤 선생님",
    "line": "여러분은 전국 보호시설의 추천을 받았고, 몇 년 동안 쌓인 생활기록을 검토한 끝에 선발됐습니다. 시험 한 번 잘 봐서 온 사람은 없어요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 45,
    "id": "scene-45",
    "speaker": "한서윤 선생님",
    "line": "다만 추천서와 선발 의견은 공개되지 않았습니다. 저도 여러분 기록의 전부를 보지 못했어요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/26_포즈5_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 46,
    "id": "scene-46",
    "speaker": "한서윤 선생님",
    "line": "그러니 서명부터 하지 마세요. 모르는 건 묻고, 마음에 걸리면 보류해도 됩니다. 여기서 처음 남길 기록은 그 이유일 테니까요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 47,
    "id": "scene-47",
    "speaker": "김학준",
    "line": "계좌 명의가 누구예요? 지금부터 저희 돈인 건지, 열아홉 살이 돼야 저희 돈이 되는 건지 다르잖아요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 48,
    "id": "scene-48",
    "speaker": "한서윤 선생님",
    "line": "현재는 국가가 관리하는 자립계좌입니다. 운용 기록은 여러분이 등록한 이름으로 남고, 열아홉 살이 되는 날 원금과 누적 수익이 개인 명의로 넘어갑니다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 49,
    "id": "scene-49",
    "speaker": "수아",
    "line": "내 돈 같긴 한데 지금은 꺼낼 수 없고, 벌면 나라가 조금 가져가고… 듣고 보니 되게 애매하네요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/05_worried_quality_v2.png",
  },
  <String, Object>{
    "order": 50,
    "id": "scene-50",
    "speaker": "한서윤 선생님",
    "line": "그 애매함을 그냥 넘기지 마세요. 왜 이상한지 자기 말로 적으면, 그게 첫 기록이 됩니다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 51,
    "id": "scene-51",
    "speaker": "나",
    "line": "돈을 공짜로 주는 건 아니네요. 돈 대신 우리가 어떻게 생각하는지 받는 거니까.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/12_thinking.png",
  },
  <String, Object>{
    "order": 52,
    "id": "scene-52",
    "speaker": "한서윤 선생님",
    "line": "맞습니다. 오늘 바로 서명할 필요는 없어요. 서명하든 보류하든, 그 이유는 남이 정해 주지 않게 하세요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 53,
    "id": "scene-53",
    "speaker": "이야기",
    "line": "통장 첫 장의 숫자는 따뜻한 종이 위에 또렷했다. 오만 원. 주머니 속 「제5기 · 17번」은 그 숫자와 상관없는 물건처럼 차갑게 남아 있었다.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 54,
    "id": "scene-54",
    "speaker": "한서윤 선생님",
    "line": "점심 전까지 생활실에 짐을 풀어 두세요. 오늘은 수업 없습니다. 처음 온 곳을 눈에 익히는 것만으로도 충분히 피곤할 테니까요.",
    "direction": "",
    "date": "2000.01.02  ·  09:00",
    "location": "국립 미래양성원 · 제6기 오리엔테이션 강당",
    "background": "/play/assets/assets/images/historical_prologue/bg_future_development_orientation_hall_2000_portrait_v1.png",
    "character": "/play/assets/assets/images/주식선생님/26_포즈5_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 55,
    "id": "scene-55",
    "speaker": "이야기",
    "line": "의자 열 개가 바닥을 짧게 긁었다. 복도에는 젖은 운동화 자국이 이어졌고, 창밖 운동장에는 아직 아무도 밟지 않은 눈이 남아 있었다.",
    "direction": "",
    "date": "2000.01.02  ·  11:28",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 56,
    "id": "scene-56",
    "speaker": "한서윤 선생님",
    "line": "복도 끝이 제6기 생활실이에요. 열 명이 같은 생활실을 쓰고, 씻거나 옷을 갈아입는 공간은 안쪽의 개별 칸으로 완전히 나뉘어 있습니다.",
    "direction": "",
    "date": "2000.01.02  ·  11:28",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 57,
    "id": "scene-57",
    "speaker": "김학준",
    "line": "남학생 둘도 여기서 같이 자요?",
    "direction": "",
    "date": "2000.01.02  ·  11:28",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 58,
    "id": "scene-58",
    "speaker": "한서윤 선생님",
    "line": "네. 어색한 게 당연해요. 오늘부터 갑자기 친한 척할 필요도 없습니다. 불편한 일이 생기면 혼자 참지만 말고 저한테 알려 주세요.",
    "direction": "",
    "date": "2000.01.02  ·  11:28",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 59,
    "id": "scene-59",
    "speaker": "이야기",
    "line": "생활실에는 이층침대 다섯 개와 사물함 열 개, 길게 붙인 공용 책상이 놓여 있었다. 침대 위에는 새 이불과 회색 입소서류 봉투가 한 묶음씩 올라가 있었다.",
    "direction": "",
    "date": "2000.01.02  ·  11:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 60,
    "id": "scene-60",
    "speaker": "한서윤 선생님",
    "line": "침상은 서로 이야기해서 정하세요. 봉투에는 일정표와 생활실 열쇠가 들어 있습니다. 이름만 확인하고, 열두 시에 식당에서 봅시다.",
    "direction": "",
    "date": "2000.01.02  ·  11:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 61,
    "id": "scene-61",
    "speaker": "수아",
    "line": "창가 위층 쓰고 싶은 사람 있어? 없으면 내가 써도 돼?",
    "direction": "",
    "date": "2000.01.02  ·  11:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/02_warm_smile_quality_v2.png",
  },
  <String, Object>{
    "order": 62,
    "id": "scene-62",
    "speaker": "한서윤 선생님",
    "line": "서로 괜찮다면 그렇게 하세요. 그럼 점심 때 볼게요.",
    "direction": "",
    "date": "2000.01.02  ·  11:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 63,
    "id": "scene-63",
    "speaker": "나",
    "line": "좋으면 그냥 먼저 올라가면 되지. 왜 물어봐?",
    "direction": "",
    "date": "2000.01.02  ·  11:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/04_curious_question.png",
  },
  <String, Object>{
    "order": 64,
    "id": "scene-64",
    "speaker": "수아",
    "line": "누가 창가 싫어하는 줄 알았는데 참고 있으면, 나중에 바꾸는 게 더 귀찮잖아. 처음에 한 번 물어보는 게 편해.",
    "direction": "",
    "date": "2000.01.02  ·  11:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/08_explaining_quality_v2.png",
  },
  <String, Object>{
    "order": 65,
    "id": "scene-65",
    "speaker": "이야기",
    "line": "한서윤이 나가자 문이 조용히 닫혔다. 방 안에는 아직 이름도 모르는 아홉 명과, 어디에 둬야 할지 모르는 짐만 남았다.",
    "direction": "",
    "date": "2000.01.02  ·  11:30",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 66,
    "id": "scene-66",
    "speaker": "이야기",
    "line": "가방을 침대 위로 들어 올리는 순간, 오래 버티던 옆선이 결국 터졌다. 셔츠와 연습장, 양말 한 짝이 바닥으로 미끄러졌다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 67,
    "id": "scene-67",
    "speaker": "이야기",
    "line": "금속 명찰도 함께 빠질 뻔했다. 나는 누구보다 먼저 손을 뻗어 그것만 주먹 안에 감췄다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 68,
    "id": "scene-68",
    "speaker": "이야기",
    "line": "아홉 쌍의 시선이 한꺼번에 내려왔다. 잠깐의 정적 뒤에, 가장 가까이 있던 여자아이가 먼저 무릎을 굽혔다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 69,
    "id": "scene-69",
    "speaker": "김서아",
    "line": "잠깐, 섞이면 더 찾기 힘들어. 네 건 이쪽에 모아 둘게. 나는 김서아야.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/02_soft_smile_agree_v1.png",
  },
  <String, Object>{
    "order": 70,
    "id": "scene-70",
    "speaker": "김서아",
    "line": "이 연습장도 네 거 맞지? 이름은 안 적혀 있네.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/01_neutral_notebook_v1.png",
  },
  <String, Object>{
    "order": 71,
    "id": "scene-71",
    "speaker": "이지안",
    "line": "가방은 멀쩡해. 옆선을 잡아 주던 실만 끊어진 거야.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/03_focused_repair_v2.png",
  },
  <String, Object>{
    "order": 72,
    "id": "scene-72",
    "speaker": "이지안",
    "line": "이지안. 바늘 있으면 다시 쓸 수 있어.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/09_explaining_mechanism_v2.png",
  },
  <String, Object>{
    "order": 73,
    "id": "scene-73",
    "speaker": "최이서",
    "line": "내가 꿰매 줄게. 이런 건 손으로 여러 번 감는 게 더 튼튼해. 최이서야.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/08_focused_mending_v1.png",
  },
  <String, Object>{
    "order": 74,
    "id": "scene-74",
    "speaker": "최이서",
    "line": "실이 검정밖에 없는데 괜찮아? 가방 색이랑 조금 다를 거야.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/08_focused_mending_v1.png",
  },
  <String, Object>{
    "order": 75,
    "id": "scene-75",
    "speaker": "정아린",
    "line": "점심까지 스물세 분 남았어. 가방은 이서가 봐주니까, 우린 침대부터 정하자. 정아린이야.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/09_counting_explain_v1.png",
  },
  <String, Object>{
    "order": 76,
    "id": "scene-76",
    "speaker": "수아",
    "line": "우리 자기소개가 왜 다 일하다가 튀어나와?",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/03_bright_laugh_quality_v2.png",
  },
  <String, Object>{
    "order": 77,
    "id": "scene-77",
    "speaker": "정아린",
    "line": "가만히 서서 한 명씩 말하는 것보단 낫잖아. 이름도 더 잘 기억되고.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/02_confident_smile_v1.png",
  },
  <String, Object>{
    "order": 78,
    "id": "scene-78",
    "speaker": "박하은",
    "line": "박하은이야. 옷은 이쪽 침대 위에 둘까? 네가 직접 하고 싶으면 그대로 놔둘게.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/02_warm_smile_v1.png",
  },
  <String, Object>{
    "order": 79,
    "id": "scene-79",
    "speaker": "나",
    "line": "괜찮아. 보여도 되는 것밖에 없어.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/04_curious_question.png",
  },
  <String, Object>{
    "order": 80,
    "id": "scene-80",
    "speaker": "박하은",
    "line": "알겠어. 그럼 이쪽에 둘게. 양말 한 짝은 침대 밑으로 갔어.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/01_base_wave_v1.png",
  },
  <String, Object>{
    "order": 81,
    "id": "scene-81",
    "speaker": "윤채아",
    "line": "연습장에도 이름이 없네.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/01_neutral_tie_v1.png",
  },
  <String, Object>{
    "order": 82,
    "id": "scene-82",
    "speaker": "윤채아",
    "line": "윤채아야. 이름을 안 쓰는 이유가 있어?",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/09_explaining_v1.png",
  },
  <String, Object>{
    "order": 83,
    "id": "scene-83",
    "speaker": "오지우",
    "line": "여기 오기 전 이름이랑, 여기서 쓸 이름을 다르게 하고 싶은 걸 수도 있지.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/oh_jiwoo/04_playful_counterpoint_v1.png",
  },
  <String, Object>{
    "order": 84,
    "id": "scene-84",
    "speaker": "윤채아",
    "line": "그건 네 추측이잖아.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/08_determined_v1.png",
  },
  <String, Object>{
    "order": 85,
    "id": "scene-85",
    "speaker": "오지우",
    "line": "맞아. 그냥 떠올라서 물어본 거야. 아니면 아닌 거고. 오지우야.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/oh_jiwoo/02_cheerful_fang_wave_v1.png",
  },
  <String, Object>{
    "order": 86,
    "id": "scene-86",
    "speaker": "수아",
    "line": "한수아. 아까 정문에서 말하긴 했는데, 너는 아직 이름 안 말했지?",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/08_explaining_quality_v2.png",
  },
  <String, Object>{
    "order": 87,
    "id": "scene-87",
    "speaker": "수아",
    "line": "정문부터 같이 왔는데 우리만 계속 너를 ‘너’라고 부르고 있어.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/06_annoyed_quality_v2.png",
  },
  <String, Object>{
    "order": 88,
    "id": "scene-88",
    "speaker": "김학준",
    "line": "김학준. 그리고 점심까지 이제 십칠 분 남았어. 이름은 말하고 싶을 때 말하면 되니까, 일단 짐부터 정리하자.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 89,
    "id": "scene-89",
    "speaker": "수아",
    "line": "학준이는 자기소개에도 남은 시간을 붙이네.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/03_bright_laugh_quality_v2.png",
  },
  <String, Object>{
    "order": 90,
    "id": "scene-90",
    "speaker": "김학준",
    "line": "안 늦는 게 중요하니까.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 91,
    "id": "scene-91",
    "speaker": "이야기",
    "line": "버스 안에서 자기소개를 세 번쯤 고쳐 생각했다. 막상 차례가 오자 준비한 문장은 하나도 입 밖으로 나오지 않았다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 92,
    "id": "scene-92",
    "speaker": "이야기",
    "line": "오른손에는 이름 없는 연습장이, 왼손에는 이름이 지워진 제5기 명찰이 들어 있었다. 둘 다 내 것이라고 말하기에는 이상한 물건이었다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 93,
    "id": "scene-93",
    "speaker": "나",
    "line": "내 이름은 내일 말할게.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/04_curious_question.png",
  },
  <String, Object>{
    "order": 94,
    "id": "scene-94",
    "speaker": "수아",
    "line": "왜 굳이 내일?",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/04_surprised_quality_v2.png",
  },
  <String, Object>{
    "order": 95,
    "id": "scene-95",
    "speaker": "나",
    "line": "내 투자장부가 생기면 첫 칸에 내가 직접 쓰고 싶어. 여기 와서 처음 생기는 내 거잖아. 쓰고 나면 알려줄게.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/12_thinking.png",
  },
  <String, Object>{
    "order": 96,
    "id": "scene-96",
    "speaker": "이야기",
    "line": "이서가 움직이던 바늘을 잠깐 멈췄다. 수아도 더 묻지 않았다. 아무도 그 말을 가볍게 받지 않았다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 97,
    "id": "scene-97",
    "speaker": "이야기",
    "line": "그날 생활실에는 이름 아홉 개와 비어 있는 한 칸이 남았다. 이상하게도 그 빈칸은 아까보다 덜 어색했다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 98,
    "id": "scene-98",
    "speaker": "정아린",
    "line": "나는 문가 아래층 쓸게. 아침에 먼저 나가도 다른 침대 안 흔들어도 되니까. 불편한 사람 있어?",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/04_assigning_tasks_v1.png",
  },
  <String, Object>{
    "order": 99,
    "id": "scene-99",
    "speaker": "이야기",
    "line": "이서가 가방 옆선을 거의 다 꿰맸을 때였다. 지안이 완성된 부분을 들어 올리고 손가락으로 몇 번 당겼다.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 100,
    "id": "scene-100",
    "speaker": "최이서",
    "line": "잠깐. 아직 안 끝났어.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/07_firm_boundary_v1.png",
  },
  <String, Object>{
    "order": 101,
    "id": "scene-101",
    "speaker": "이지안",
    "line": "끊어지나 보려고 했어.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/03_focused_repair_v2.png",
  },
  <String, Object>{
    "order": 102,
    "id": "scene-102",
    "speaker": "최이서",
    "line": "확인하고 싶으면 말해 줘. 내가 만든 걸 갑자기 잡아당기면 싫어.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/07_firm_boundary_v1.png",
  },
  <String, Object>{
    "order": 103,
    "id": "scene-103",
    "speaker": "정아린",
    "line": "지안아, 일단 내려놔. 다시 터지면 점심도 못 가.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/07_deadline_annoyed_v1.png",
  },
  <String, Object>{
    "order": 104,
    "id": "scene-104",
    "speaker": "박하은",
    "line": "아린아, 잠깐. 이서가 아직 지안이한테 할 말 있잖아.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/09_explaining_v1.png",
  },
  <String, Object>{
    "order": 105,
    "id": "scene-105",
    "speaker": "정아린",
    "line": "아… 알겠어. 이서가 싫었다는 얘기지.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/05_startled_v1.png",
  },
  <String, Object>{
    "order": 106,
    "id": "scene-106",
    "speaker": "박하은",
    "line": "응. 지안이가 직접 들으면 돼.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/09_explaining_v1.png",
  },
  <String, Object>{
    "order": 107,
    "id": "scene-107",
    "speaker": "이지안",
    "line": "미안. 궁금해서 그냥 손댔어. 다음엔 먼저 물어볼게.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/07_apologetic_boundary_v2.png",
  },
  <String, Object>{
    "order": 108,
    "id": "scene-108",
    "speaker": "최이서",
    "line": "응. 보여주는 건 괜찮아. 말만 먼저 해 줘.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/choi_iseo/02_gentle_smile_v1.png",
  },
  <String, Object>{
    "order": 109,
    "id": "scene-109",
    "speaker": "이지안",
    "line": "알겠어. 그리고 이거, 생각보다 훨씬 튼튼해.",
    "direction": "",
    "date": "2000.01.02  ·  11:37",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/lee_jian/02_playful_wink_v2.png",
  },
  <String, Object>{
    "order": 110,
    "id": "scene-110",
    "speaker": "이야기",
    "line": "점심 종이 울렸고, 열 명은 식당으로 내려갔다. 돌아왔을 때 회색 입소서류 봉투가 각자의 침대 위에 그대로 놓여 있었다.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 111,
    "id": "scene-111",
    "speaker": "김서아",
    "line": "이상한데. 서류 번호가 3에서 5로 건너뛰어. 열 개 다 똑같아.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/05_surprised_record_v1.png",
  },
  <String, Object>{
    "order": 112,
    "id": "scene-112",
    "speaker": "박하은",
    "line": "4번이 뭐였는데?",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/05_surprised_v1.png",
  },
  <String, Object>{
    "order": 113,
    "id": "scene-113",
    "speaker": "김서아",
    "line": "목차에는 ‘선발 의견서’라고 적혀 있어. 그런데 우리 봉투에는 그 페이지만 없어.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/kim_seoa/09_explaining_ledger_v1.png",
  },
  <String, Object>{
    "order": 114,
    "id": "scene-114",
    "speaker": "이야기",
    "line": "종이 넘기는 소리가 방 안에서 연달아 났다. 누구의 봉투에도 선발 의견서는 들어 있지 않았다.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 115,
    "id": "scene-115",
    "speaker": "윤채아",
    "line": "실수는 아니야. 열 명 전부 같은 페이지를 뺐잖아.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/08_determined_v1.png",
  },
  <String, Object>{
    "order": 116,
    "id": "scene-116",
    "speaker": "정아린",
    "line": "그럼 선생님한테 바로 물어보자. 안 알려 주는 이유가 있는지.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/jung_arin/08_determined_ready_v1.png",
  },
  <String, Object>{
    "order": 117,
    "id": "scene-117",
    "speaker": "오지우",
    "line": "바로 묻는 건 찬성. 근데 먼저 확인할 건 있어. 선생님도 못 봤다고 했잖아. 숨긴 사람이 선생님이라는 보장은 없어.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/oh_jiwoo/06_skeptical_thinking_v1.png",
  },
  <String, Object>{
    "order": 118,
    "id": "scene-118",
    "speaker": "박하은",
    "line": "그러면 몰아세우지 말고 같이 묻자. 우리 모두 같은 페이지가 없었다는 것부터.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/park_haeun/09_explaining_v1.png",
  },
  <String, Object>{
    "order": 119,
    "id": "scene-119",
    "speaker": "이야기",
    "line": "처음으로 열 명의 시선이 같은 곳에 모였다. 서로의 이름보다 먼저, 자신들이 왜 이곳에 왔는지가 방 한가운데 놓였다.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 120,
    "id": "scene-120",
    "speaker": "수아",
    "line": "선생님은 우리가 몇 년 동안 어떤 선택을 했는지 봤다고 했어. 그런데 정작 우리는 그 기록을 한 줄도 못 보는 거네.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/05_worried_quality_v2.png",
  },
  <String, Object>{
    "order": 121,
    "id": "scene-121",
    "speaker": "오지우",
    "line": "혹시 뽑힌 이유보다, 뽑힌 뒤에 우리가 어떻게 움직이는지가 진짜 시험이면?",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/oh_jiwoo/06_skeptical_thinking_v1.png",
  },
  <String, Object>{
    "order": 122,
    "id": "scene-122",
    "speaker": "윤채아",
    "line": "어느 쪽이든 확인해야 해. 자기 추천서나 선발 기록을 직접 본 사람 있어?",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/yoon_chaea/09_explaining_v1.png",
  },
  <String, Object>{
    "order": 123,
    "id": "scene-123",
    "speaker": "이야기",
    "line": "아무도 손을 들지 않았다. 학준은 입소 안내서의 연혁 부분을 다시 펼쳤고, 나는 주머니 속 명찰 모서리를 엄지로 눌렀다.",
    "direction": "",
    "date": "2000.01.02  ·  13:05",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 124,
    "id": "scene-124",
    "speaker": "이야기",
    "line": "딸깍. 주머니에서 빠져나온 명찰이 바닥을 한 번 튕겼다. 내가 손을 뻗었을 때, 맞은편의 학준은 이미 글자를 읽은 뒤였다.",
    "direction": "",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 125,
    "id": "scene-125",
    "speaker": "김학준",
    "line": "제5기 명찰이야? 이상해. 입소 안내서 연혁에는 1기부터 4기까지 있는데, 5기 기록만 한 줄도 없어.",
    "direction": "",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 126,
    "id": "scene-126",
    "speaker": "수아",
    "line": "숨기려면 그렇게 자꾸 주머니를 만지면 안 돼. 보여 주기 싫으면 안 봐도 돼. 그런데 우리 선발 기록이랑 이어지는 거라면, 나도 알고 싶어.",
    "direction": "",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/05_worried_quality_v2.png",
  },
  <String, Object>{
    "order": 127,
    "id": "scene-127",
    "speaker": "나",
    "line": "새봄보육원 가방 안감에서 나왔어. 뒤에는 「17번을 믿지 마」라고 적혀 있고. 아직 선생님한테는 말 안 했어.",
    "direction": "",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "/play/assets/assets/images/protagonist_seed01/17_holding_badge.png",
  },
  <String, Object>{
    "order": 128,
    "id": "scene-128",
    "speaker": "김학준",
    "line": "원본은 네가 가지고 있어. 우리는 적힌 글자랑 발견 장소만 따로 써 두자. 내일 자료실부터 찾아보고, 5기 기록이 정말 없는지 확인하자.",
    "direction": "",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 129,
    "id": "scene-129",
    "speaker": "수아",
    "line": "선생님부터 의심하진 말자. 그렇다고 그냥 넘기지도 말고. 우리 셋이 같은 사실을 확인한 다음에 물어보는 거야.",
    "direction": "",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "/play/assets/assets/images/production_soft_painted/han_sua/07_determined_quality_v2.png",
  },
  <String, Object>{
    "order": 130,
    "id": "scene-130",
    "speaker": "이야기",
    "line": "밤 아홉 시 사십 분. 열 개의 침상에서 이불이 하나씩 부풀었다. 낯선 숨소리 사이에서 오만 원짜리 계좌와 사라진 선발 의견서, 제5기 17번만 오래 잠들지 않았다.",
    "direction": "",
    "date": "2000.01.02  ·  21:34",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_night_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 131,
    "id": "scene-131",
    "speaker": "이야기",
    "line": "다음 날 오전 8시 40분. 겨울 햇빛이 침상 난간과 사물함 손잡이를 차례로 훑었다. 열 명은 같은 공책을 한 권씩 끼고 생활실을 나섰다.",
    "direction": "",
    "date": "2000.01.03  ·  08:40",
    "location": "국립 미래양성원 · 제6기 공용 생활실",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_shared_room_day_2000_v1.png",
    "character": "",
  },
  <String, Object>{
    "order": 132,
    "id": "scene-132",
    "speaker": "한서윤 선생님",
    "line": "첫 수업은 PC 실습실에서 합니다. 오늘은 회사와 주식 한 주가 무엇인지 화면으로 직접 확인할 거예요. 실제 주문은 아직 나가지 않습니다.",
    "direction": "",
    "date": "2000.01.03  ·  08:55",
    "location": "국립 미래양성원 · 기숙사 중앙 복도",
    "background": "/play/assets/assets/images/cinematic_soft_painted/dormitory_2000/bg_future_academy_dorm_corridor_2000_v1.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 133,
    "id": "scene-133",
    "speaker": "이야기",
    "line": "문이 열리자 베이지색 본체와 두꺼운 브라운관 모니터가 두 줄로 늘어서 있었다. 묵직한 키보드와 줄 달린 볼마우스, 벽을 따라 이어진 회색 통신선. 미지근한 플라스틱 냄새 사이로 오래된 먼지 냄새가 섞여 있었다.",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "",
  },
  <String, Object>{
    "order": 134,
    "id": "scene-134",
    "speaker": "한서윤 선생님",
    "line": "오늘부터 한 사람당 컴퓨터 한 대를 맡습니다. 번호를 확인하고 앉으세요. 화면이 뜨기 전에는 아직 누구의 장부도 만들어지지 않습니다.",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 135,
    "id": "scene-135",
    "speaker": "김학준",
    "line": "전원을 켜면 바로 주식을 살 수 있습니까?",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/historical_prologue/character_hakjun_orientation_v2.png",
  },
  <String, Object>{
    "order": 136,
    "id": "scene-136",
    "speaker": "한서윤 선생님",
    "line": "아니요. 먼저 회사를 여러 사람이 나눠 가진다는 뜻부터 배울 겁니다. 그중 아주 작은 한 조각이 주식 한 주예요. 가격은 그 조각을 사고 싶은 사람과 팔고 싶은 사람이 만나 정하고요.",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/주식선생님/23_포즈2_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 137,
    "id": "scene-137",
    "speaker": "한서윤 선생님",
    "line": "자기 번호 앞에 앉으세요. 전원 버튼은 제가 말한 뒤에 누릅니다.",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/주식선생님/22_포즈1_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 138,
    "id": "scene-138",
    "speaker": "이야기",
    "line": "내 자리는 06번이었다. 꺼진 모니터 한가운데 손바닥 자국이 하나 남아 있었다. 내 손보다 컸고, 오래된 먼지 위에 찍힌 것치고는 지나치게 선명했다.",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "",
  },
  <String, Object>{
    "order": 139,
    "id": "scene-139",
    "speaker": "한서윤 선생님",
    "line": "이제 전원을 켜세요. 화면이 뜨면 아무것도 누르지 말고, 처음 보이는 문장을 그대로 읽습니다.",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/주식선생님/24_포즈3_주인공그림체_공통슬롯_투명.png",
  },
  <String, Object>{
    "order": 140,
    "id": "scene-140",
    "speaker": "한서윤 선생님",
    "line": "06번 학생은 잠깐만요. 그 자리는 지난해 제5기 06번이 쓰던 자리였습니다. 그런데 그 번호는 수료 명단에 없습니다.",
    "direction": "",
    "date": "2000.01.03  ·  09:00",
    "location": "국립 미래양성원 · 주식 PC 실습실",
    "background": "/play/assets/assets/images/bg_stock_academy_2000_portrait_cartoon_v4.png",
    "character": "/play/assets/assets/images/주식선생님/26_포즈5_주인공그림체_공통슬롯_투명.png",
  },
];
